### ISSUE TITLE
Chrome ARC support please

### ISSUE THREAD

**Issue by MufriA** [sqlcipher/android-database-sqlcipher#156]
Tried to run app which used sqlcipher, db fails to open with error

      W/libposix_translation_static(  204): O_CLOEXEC is not supported

Any plans for Chrome ARC?

https://developer.chrome.com/apps/getstarted_arc

**Comment by developernotes** [comment]
Hello @MufriA 

Chrome ARC certainly looks interesting and it sounds like SQLCipher for Android would benefit from being able to run on Chrome.  I'm unfamiliar with how new Chrome ARC is, however it appears they do not support `O_CLOEXEC` within their [master](https://chromium.googlesource.com/arc/arc/+/master/src/posix_translation/pepper_file.cc) branch.

**Comment by MufriA** [comment]
Looks like google is working on it https://code.google.com/p/chromium/issues/detail?id=465683

**Comment by brodybits** [comment]
> Looks like google is working on it https://code.google.com/p/chromium/issues/detail?id=465683

Seems to be fixed now, at least in their "latest runtime" 43.5021.45.0.

**Comment by McPo** [comment]
Ran into this issue with 45.5021.416.0

**Comment by McPo** [comment]
Turns out I was looking at the version of ART Welder and not the runtime. The runtime can be found within the extensions page after installing the welder extension.

I am currently on 43.4410.349.18
Ill update this page once Ive found a way to get the latest version, if possible.

**Comment by fraglord94** [comment]
I am getting  InvocationTargetException possibly when the database is being created.
Stacktrace at chrome://inspect/apps#apps

```
----------------------------------------
ARC Window Popup: 43.508ms
ARC appWindow Init: 1.936ms
ARC onInstalled HTML5 FS init: 356.065ms
Received a crash
prod: ARC
arc_app_name: *******
ptime: 3090.26100000483
crash_time: Mon Aug 03 2015 10:35:48 GMT+0530 (India Standard Time)
ver: 44.4410.376.13
arc_build_tag: arc-runtime-44.4410.376.13
message: Android unhandled exception
chrome_version: 44.0.2403.125
app_id: lpenmipoimkolgnmcncipajdpdglcneh
app_version: 0.9
app_package_name: com.*******
runtime_name: App Runtime for Chrome (Beta)
runtime_update_url: https://clients2.google.com/service/update2/crx
width: 960
height: 632
is_minimized: false
is_maximized: false
is_fullscreen: false
runtime_updated_while_running: null
log_message: net.sqlcipher.database.SQLiteException
stack_trace: java.lang.RuntimeException
	at android.os.Process$1.run(Process.java:425)
Caused by java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at android.os.Process$1.run(Process.java:418)
Caused by java.lang.RuntimeException
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4439)
	at android.app.ActivityThread.access$1400(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:5291)
	...3 more
Caused by net.sqlcipher.database.SQLiteException
	at net.sqlcipher.database.SQLiteDatabase.dbopen(Native Method)
	at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:1922)
	at *******.android.importfromasset.ImportUnencryptedDatabase.execute(ImportUnencryptedDatabase.java:59)
	at com.*******.android.*******DatabaseLibrary.copyDataBase(*******DatabaseLibrary.java:204)
	at com.*******.android.*******DatabaseLibrary.initialize(*******DatabaseLibrary.java:100)
	at com.*******.android.*******DatabaseLibrary.<init>(*******DatabaseLibrary.java:74)
	at com.*******.android.*******DatabaseLibrary.getInstance(*******DatabaseLibrary.java:159)
	at com.*******.android.*******AndroidApplicationContext.setDaoSession(*******AndroidApplicationContext.java:238)
	at com.*******.android.*******AndroidApplicationContext.setApplicationContext(*******AndroidApplicationContext.java:222)
	at com.*******.android.*******AndroidApplicationContext.onCreate(*******AndroidApplicationContext.java:211)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4436)
	...8 more

sig: net.sqlcipher.database.SQLiteException-d2d0ebd8
arch: x86-32
nacl_arch: x86-64
os: win
Crash reporting not enabled in Chrome.  Please enable it.
FINISHED REPORTING CRASH
------------------------------
```

**Comment by Tapchicoma** [comment]
Seems this issue can be closed as Google will not support ARC any more, but done it with other approach: [link to some details](http://arstechnica.com/gadgets/2016/05/the-play-store-comes-to-chrome-os-but-not-the-way-we-were-expecting/).
