### ISSUE TITLE
file is encrypted or is not a database

### ISSUE THREAD

**Issue by chetan1011** [sqlcipher/android-database-sqlcipher#160]
Hi boss,

net.sqlcipher.database.SQLiteException: file is encrypted or is not a database

**Comment by developernotes** [comment]
Hi @chetan1011 

Do you have a specific question regarding the `SQLiteException`?

**Comment by AmirHadifar** [comment]
@developernotes 
Hi I have same issue , I have a database in my asset folder in first load of application I copied it to Data/data/<packageName>/database and then use it . when I use 

SQLiteDatabase db = this.getReadableDatabase(PASSWORD_OF_DB);

if  i set password as null or "" its work fine but when I set a password it throws such exception : 

05-02 18:23:52.700  13942-13942/com.essentialwords.amir.essentialwords E/Database﹕ Failed to setLocale() when constructing, closing the database
    net.sqlcipher.database.SQLiteException: file is encrypted or is not a database
            at net.sqlcipher.database.SQLiteDatabase.native_setLocale(Native Method)
            at net.sqlcipher.database.SQLiteDatabase.setLocale(SQLiteDatabase.java:2096)
            at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:1962)
            at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:881)
            at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:913)
            at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:132)
            at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:197)
            at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:184)
            at com.essentialwords.amir.essentialwords.MyDbHelper.closeDB(MyDbHelper.java:347)
            at com.essentialwords.amir.essentialwords.DrawerLayoutActivity.initDatabase(DrawerLayoutActivity.java:110)
            at com.essentialwords.amir.essentialwords.DrawerLayoutActivity.onCreate(DrawerLayoutActivity.java:35)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Could you help me to solve this problem Sir ?

**Comment by developernotes** [comment]
Hello @AmirHadifar 

Is the database located in your `assets` folder encrypted, or is it a plain-text database?

**Comment by AmirHadifar** [comment]
@developernotes 
it's not encrypted. it's simple database which I create it with sqliteBrowser

**Comment by developernotes** [comment]
Hello @AmirHadifar 

You can not provide a password to a plain text database, there is nothing to decrypt.  If you wish to import the plain text database and make it encrypted, you will need to use the [`sqlcipher_export(…)`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) convenience function, specifically example 1 in the documentation.

**Comment by chetan1011** [comment]
Hi Sir,
 I have same issue , I have a database in my external folder(sd card). when I use

SQLiteDatabase db = this.getReadableDatabase(PASSWORD_OF_DB);

it throws such exception :
07-04 16:10:09.110: W/System.err(3642): net.sqlcipher.database.SQLiteException: file is encrypted or is not a database
07-04 16:10:09.111: W/System.err(3642): 	at net.sqlcipher.database.SQLiteDatabase.native_setLocale(Native Method)
07-04 16:10:09.111: W/System.err(3642): 	at net.sqlcipher.database.SQLiteDatabase.setLocale(SQLiteDatabase.java:2096)
07-04 16:10:09.111: W/System.err(3642): 	at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:1962)
07-04 16:10:09.111: W/System.err(3642): 	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:881)
07-04 16:10:09.111: W/System.err(3642): 	at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:913)
07-04 16:10:09.111: W/System.err(3642): 	at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:132)
07-04 16:10:09.111: W/System.err(3642): 	at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:99)
07-04 16:10:09.111: W/System.err(3642): 	at com.esense.topscorer.scratchcard.DataInitialization.getSDCardData(DataInitialization.java:47)
07-04 16:10:09.111: W/System.err(3642): 	at com.esense.topscorer.scratchcard.DataInitialization.setSDCardData(DataInitialization.java:59)
07-04 16:10:09.111: W/System.err(3642): 	at com.esense.topscorer.scratchcard.BaseActivity.setConnection(BaseActivity.java:97)

**Comment by developernotes** [comment]
Hello @chetan1011 

Can you try the SQLCipher for Android source in the master branch?  This may provide a more specific error message for you.

**Comment by lavzchen** [comment]
hello @developernotes ，i have some error too， i create database by onCreate() 

CREATE TABLE android_metadata failed
Failed to setLocale() when constructing, closing the database
net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: create locale table failed
at net.sqlcipher.database.SQLiteDatabase.native_setLocale(Native Method)
at net.sqlcipher.database.SQLiteDatabase.setLocale(SQLiteDatabase.java:2316)
at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:2181)
at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1000)
at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1043)
at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:132)
at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:99)
at phdi.it.storeapp.zbf.Utils.YumDBHelper.insertUploadLog(YumDBHelper.java:225)
at phdi.it.storeapp.zbf.Utils.LogUtils.dbLog(LogUtils.java:48)
at phdi.it.storeapp.zbf.Activity.LanuchActivity$2.run(LanuchActivity.java:115)

**Comment by developernotes** [comment]
Hello @lavzchen 

Are you able to reproduce the error with the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on the particular device/emulator you are seeing the error on?

**Comment by chetan1011** [comment]
Hello @developernotes 

net.sqlcipher.database.SQLiteException: file is encrypted or is not a database .

now this error is there any solution.?

**Comment by developernotes** [comment]
Hello @chetan1011 

It is possible that you may not have permissions to write to the SD card.  Can you try moving the database file before you open your connection to see if that is the issue?
