### ISSUE TITLE
NPE error in SQLiteProgram.java#L113

### ISSUE THREAD

**Issue by narakim** [sqlcipher/android-database-sqlcipher#186]
I'm getting a null pointer exception in https://github.com/sqlcipher/android-database-sqlcipher/blob/v3.0.2/src/net/sqlcipher/database/SQLiteProgram.java#L113

It seems like a threading issue because the local variable mCompiledSql can be re-defined by other threads in L80. https://github.com/sqlcipher/android-database-sqlcipher/blob/v3.0.2/src/net/sqlcipher/database/SQLiteProgram.java#L80

Caused by: java.lang.NullPointerException: Attempt to read from field 'int net.sqlcipher.database.SQLiteCompiledSql.nStatement' on a null object reference
	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:113)
	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1441)
	at net.sqlcipher.database.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1321)
	at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:1275)
	at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:1395)

**Comment by developernotes** [comment]
Hello @narakim 

Can you reproduce the behavior you are seeing within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by narakim** [comment]
This came up in production releases so I don't know how to reproduce it with the given test suite. 

The code makes sense though. Shouldn't mCompiledSql be synchronized?

**Comment by developernotes** [comment]
Hello @narakim 

I am not certain a change is necessary without further evidence of an issue.  If you can put together a test scenario in the suite that replicates the issue we would be glad to take a look into it.
