### ISSUE TITLE
Bug:  java.lang.IllegalMonitorStateException  

### ISSUE THREAD

**Issue by LiHanGuang** [sqlcipher/android-database-sqlcipher#201]
Hello:
I get into trouble,  but i am not sure that the bug is belonged to "android-database-sqlcipher".
if the bug is belonged to "android-database-sqlcipher", please show me the code how to fix it, thanks.

- **Version: 3.2.0**

- **log**
```java
stackTrace: 	
java.lang.RuntimeException: An error occured while executing doInBackground()	
at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)	
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)	
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)	
at java.util.concurrent.FutureTask.run(FutureTask.java:242)	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)	
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.IllegalMonitorStateException	
at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:122)	
at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1238)	
at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:428)	
at net.sqlcipher.database.SQLiteDatabase.unlock(SQLiteDatabase.java:476)	
at net.sqlcipher.database.SQLiteQuery.fillWindow(SQLiteQuery.java:93)	
at net.sqlcipher.database.SQLiteCursor.fillWindow(SQLiteCursor.java:290)	
at net.sqlcipher.database.SQLiteCursor.getCount(SQLiteCursor.java:271)	
at android.database.CursorWrapper.getCount(CursorWrapper.java:57)	
at com.jiahe.qixin.JeCursorLoader.loadInBackground(JeCursorLoader.java:22)	
at com.jiahe.qixin.JeCursorLoader.loadInBackground(JeCursorLoader.java:7)	
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)	
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)	
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)	
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)	
at java.util.concurrent.FutureTask.run(FutureTask.java:237)	
```

- **code**
```java
CODE 1: my custom loader.
public abstract class JeCursorLoader extends CursorLoader {

	private static final String TAG = JeCursorLoader.class.getSimpleName();

	public JeCursorLoader(Context context) {
		super(context);
	}

	protected abstract Cursor loadCursor();  // do some  raw query here.

	@Override
	public Cursor loadInBackground() {
		Cursor localCursor = loadCursor();

		if (localCursor != null) {
			localCursor.getCount();  // i am here !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
		}

		return localCursor;
	}

}


CODE 2: 
src/net/sqlcipher/database/SQLiteQuery.java

    /* package */ int fillWindow(CursorWindow window,
            int maxRead, int lastPos) {
        long timeStart = SystemClock.uptimeMillis();
        mDatabase.lock();
        mDatabase.logTimeStat(mSql, timeStart, SQLiteDatabase.GET_LOCK_LOG_PREFIX);
        try {
            acquireReference();
            try {
                window.acquireReference();
                // if the start pos is not equal to 0, then most likely window is
                // too small for the data set, loading by another thread
                // is not safe in this situation. the native code will ignore maxRead
                int numRows = native_fill_window(window, window.getStartPosition(), mOffsetIndex,
                        maxRead, lastPos);

                // Logging
                if (SQLiteDebug.DEBUG_SQL_STATEMENTS) {
                    Log.d(TAG, "fillWindow(): " + mSql);
                }
                mDatabase.logTimeStat(mSql, timeStart);
                return numRows;
            } catch (IllegalStateException e){
                // simply ignore it
                return 0;
            } catch (SQLiteDatabaseCorruptException e) {// An exception that indicates that the SQLite database file is corrupt. 
                mDatabase.onCorruption(); // maybe  calls unlock here !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                throw e;
            } finally {
                window.releaseReference();
            }
        } finally {
            releaseReference();
            mDatabase.unlock();
        }
    }
```

**Comment by developernotes** [comment]
Hello @LiHanGuang 

Can you create a unit test within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) that reproduces the issue?  If so, we would be glad to take a look into it.  Thanks!

**Comment by LiHanGuang** [comment]
@developernotes 

maybe this problem 

https://discuss.zetetic.net/t/file-is-encrypted-or-is-not-a-database-after-upgrade-sqlcipher-from-v-2-2-2-0-to-v-3-1-0/227

**Comment by developernotes** [comment]
Hello @LiHanGuang 

Being unable to open a database connection due to the file format is unlikely to produce an `IllegalMonitorStateException` which you reported above.  Have you been able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?
