### ISSUE TITLE
Errors migrating database from unencrypted version in android 6

### ISSUE THREAD

**Issue by Raiv** [sqlcipher/android-database-sqlcipher#209]
As I can see in docs , when I do `ATTACH DATABASE ...` it should create database file to attach if it not exists.
That failed with "Could not open database" exception.
OK, I created database to attach with `SQLiteDatabase.openOrCreateDatabase(newDbf, password, null);`
It crushes on `"SELECT sqlcipher_export('encrypted');`" saying "table android_metadata already exists".
Finally I came to code below, with two workarounds 
1) Create db to export to manually
2) Drop autocreated table android_metadata
After that all finally worked. 
```java
            File newDbf = ApplicationPinbonus.getInstance().getDatabasePath(DBHelper.DB_NAME);
            if(!newDbf.exists())
            {
                newDbf.mkdirs();
            }else{
                newDbf.delete();
            }
            String token = NetworkManager.getInstance().getToken();
            String password = DataEncoder.getPass(token);
            //1. make empty encrypted db
           SQLiteDatabase newDb =SQLiteDatabase.openOrCreateDatabase(newDbf, password, null);
            //remove autogenerated tables
            newDb.rawExecSQL("drop table android_metadata;");
        //newDb.
           newDb.close();

            // open old, export values
            SQLiteDatabase db = SQLiteDatabase.openDatabase(oldDb.getAbsolutePath(), "", null, SQLiteDatabase.OPEN_READWRITE);

            try {
                String attachString =String.format("ATTACH DATABASE '%s' AS 'encrypted' KEY '%s';",
                        newDbf.getAbsolutePath(), password) ;
                db.rawExecSQL(attachString);
                db.rawExecSQL("SELECT sqlcipher_export('encrypted');");
                db.rawExecSQL("DETACH DATABASE 'encrypted';");
                int version = db.getVersion();
               db.close();
                //open new, update version
                db = SQLiteDatabase.openDatabase(newDbf.getAbsolutePath(), password, null, SQLiteDatabase.OPEN_READWRITE);
                db.setVersion(version);
                //delete old
                oldDb.delete();
            }finally {
                db.close();
            }
```

OS android 6.0.1 , Nexus 5
sqlcipher version 3.3.1_2

**Comment by developernotes** [comment]
Hi @Raiv 

Are you able to recreate your issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?  The attached database will only be created when it does not already exist.  The `android_metadata` table will only be created when it [does not already exist](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/jni/net_sqlcipher_database_SQLiteDatabase.cpp#L488-L519).

**Comment by Raiv** [comment]
All tests passed succesfully... That is strange. If you look in my code, i delete database file if it exists just to be sure ...
BTW, your test suites repo contains old sqlcipher binaries and libs

**Comment by developernotes** [comment]
Hi @Raiv 

I've updated the test suite.  Is it possibly the file is not being deleted, possibly an invalid file path?

**Comment by Raiv** [comment]
I updated the code to be sure that db file does not exists. Here is the code and log:
```Java
private void migrateDB(File oldDb){

      //  synchronized (Database.class) { must be called in sync!
            File newDbf = ApplicationPinbonus.getInstance().getDatabasePath(DBHelper.DB_NAME);
            boolean needCreateManually = false;
            if(!newDbf.exists())
            {
                Log.d(TAG, "no files found! "+newDbf.getAbsolutePath());
                newDbf.mkdirs();
            }else{
                Log.d(TAG, "file found!"+newDbf.getAbsolutePath());
                if(!newDbf.delete())
                {
                    Log.e(TAG,"Unable to delete ciphered db file!");
                    needCreateManually =true;
                }
            }
            String token = NetworkManager.getInstance().getToken();
            String password = DataEncoder.getPass(token);
            if(needCreateManually) {
                //1. make empty encrypted db
                SQLiteDatabase newDb = SQLiteDatabase.openOrCreateDatabase(newDbf, password, null);
                //remove autogenerated tables
                newDb.rawExecSQL("drop table android_metadata;");
                //newDb.
                newDb.close();
            }
            // open old, export values
            SQLiteDatabase db = SQLiteDatabase.openDatabase(oldDb.getAbsolutePath(), "", null, SQLiteDatabase.OPEN_READWRITE);

            try {
                String attachString =String.format("ATTACH DATABASE '%s' AS 'encrypted' KEY '%s';",
                        newDbf.getAbsolutePath(), password) ;
                db.rawExecSQL(attachString);
                db.rawExecSQL("SELECT sqlcipher_export('encrypted');");
                db.rawExecSQL("DETACH DATABASE 'encrypted';");
                int version = db.getVersion();
                db.close();
                //open new, update version
                db = SQLiteDatabase.openDatabase(newDbf.getAbsolutePath(), password, null, SQLiteDatabase.OPEN_READWRITE);
                db.setVersion(version);
                //delete old
                oldDb.delete();
            }catch (SQLiteException e) {
                Log.e(TAG,"Error exporting database!!!",e);
            }
            finally {
                db.close();
            }

       // }


    }
```

```
12-29 16:52:58.769 13960-13960/com.pinbonus2:ui D/Database: no files found! /data/user/0/com.pinbonus2/databases/pinbonussqc.db
12-29 16:52:58.780 13960-13960/com.pinbonus2:ui I/Database: sqlite returned: error code = 14, msg = cannot open file at line 34892 of [2ef4f3a5b1]
12-29 16:52:58.780 13960-13960/com.pinbonus2:ui I/Database: sqlite returned: error code = 14, msg = os_unix.c:34892: (21) open(/data/user/0/com.pinbonus2/databases/pinbonussqc.db) - 
12-29 16:52:58.780 13960-13960/com.pinbonus2:ui I/Database: sqlite returned: error code = 14, msg = statement aborts at 5: [ATTACH DATABASE '/data/user/0/com.pinbonus2/databases/pinbonussqc.db' AS 'encrypted' KEY '5d8348e0f33805cb0fa5a447b46e61d46b5eda3b';] unable to open database: /data/user/0/com.pinbonus2
12-29 16:52:58.781 13960-13960/com.pinbonus2:ui E/Database: Error exporting database!!!
                                                            net.sqlcipher.database.SQLiteException: unable to open database: /data/user/0/com.pinbonus2/databases/pinbonussqc.db
                                                                at net.sqlcipher.database.SQLiteDatabase.native_rawExecSQL(Native Method)
                                                                at net.sqlcipher.database.SQLiteDatabase.rawExecSQL(SQLiteDatabase.java:2183)
                                                                at com.pinbonus.db.Database.migrateDB(Database.java:94)
                                                                at com.pinbonus.db.Database.initDB(Database.java:125)
                                                                at com.pinbonus.db.Database.getData(Database.java:338)
                                                                at com.pinbonus.db.Database.getData(Database.java:359)
                                                                at com.pinbonus.common.network.QueuedRequestHelper.restoreQueue(QueuedRequestHelper.java:89)
                                                                at com.pinbonus.common.network.NetworkManager.<init>(NetworkManager.java:120)
                                                                at com.pinbonus.common.network.NetworkManager.getInstance(NetworkManager.java:371)
                                                                at com.pinbonus.ApplicationPinbonus$InitAllTrackersRunnable.run(ApplicationPinbonus.java:1247)
                                                                at com.pinbonus.ActivitySplash$2.run(ActivitySplash.java:448)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:148)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

All tests passed succesfully. 
I do not know why this might happen. Maybe some permissions issues... Code runs on UI thread.

**Comment by developernotes** [comment]
Hi @Raiv 

What version of SQLCipher for Android are you using?  What happens if you always execute `newDbf.mkdirs();`?  Can you write a small test within the [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) that recreates it for further review?

**Comment by Raiv** [comment]
I'll try it in a few days.

**Comment by Raiv** [comment]
I failed to reproduce this in test app(
Well, maybe  close this. I have a working walkaround, so it's not so critical.
