### ISSUE TITLE
App is crashing in older versions than lollipop

### ISSUE THREAD

**Issue by nabeelpkl** [sqlcipher/android-database-sqlcipher#229]
I am getting following error while running my application in android kitkat or older versions.
error:

```
04-26 18:26:26.095 4996-4996/packageName E/dalvikvm: Could not find class 'net.sqlcipher.DefaultDatabaseErrorHandler', referenced from method net.sqlcipher.database.SQLiteOpenHelper.<init>
04-26 18:26:26.125 4996-4996/packageName E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            java.lang.VerifyError: net/sqlcipher/database/SQLiteOpenHelper
                                                                                at packageName.database.PassbookContentProvider.onCreate(PassbookContentProvider.java:537)
                                                                                at android.content.ContentProvider.attachInfo(ContentProvider.java:1214)
                                                                                at android.content.ContentProvider.attachInfo(ContentProvider.java:1189)
                                                                                at android.app.ActivityThread.installProvider(ActivityThread.java:5119)
                                                                                at android.app.ActivityThread.installContentProviders(ActivityThread.java:4725)
                                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4665)
                                                                                at android.app.ActivityThread.access$1400(ActivityThread.java:159)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                at android.os.Looper.loop(Looper.java:176)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5419)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
                                                                                at dalvik.system.NativeStart.main(Native Method)

```

I am stuck please help.

**Comment by developernotes** [comment]
Hi @nabeelpkl 

What version of SQLCipher for Android are you running?

**Comment by nabeelpkl** [comment]
I used older version with which is a jar file(don't know the version). and also tried this 
    compile 'net.zetetic:android-database-sqlcipher:3.3.1-2@aar'

both giving same error.

**Comment by developernotes** [comment]
@nabeelpkl 

Would you run the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on that device and share your results?

**Comment by nabeelpkl** [comment]
Ok let me try

**Comment by nabeelpkl** [comment]
the app is working just fine. didn't face any problem.

**Comment by dbrgn** [comment]
I'm facing the same problem on one of my test devices (Android 4.2), but not the other one (Android 5.0.1).

```
E/Threema: java.lang.VerifyError: net/sqlcipher/database/SQLiteDatabase
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.VerifyError: net/sqlcipher/database/SQLiteDatabase
```

I think the issue started when I enabled Multidex. [This](http://stackoverflow.com/a/37003814/284318) post on SO also hints at that. Is this a known problem?

**Comment by developernotes** [comment]
Hi @dbrgn 

This is not a known problem, however our Android application does not utilize multidex. Can you try modifying your application so you can disable multidex and let us know your results? Thanks!

**Comment by dbrgn** [comment]
@developernotes right now that's not possible, as we're over the method limit allowed without multidex due to 1-2 large libraries. But I'm currently working on a development branch. The main branch with the same sqlcipher version (and no multidex) works properly.

**Comment by developernotes** [comment]
Hello @dbrgn 

It is difficult to say what is occurring with multidex that is preventing your application from running. From the [limitations](https://developer.android.com/studio/build/multidex.html#limitations) that Google has published, it sounds as if it may be important for certain classes to be placed within the primary dex file which if not there could prevent the library from operating correctly. It may be worth aggressively applying the [guidance](https://developer.android.com/studio/build/multidex.html#avoid) from Google to decrease your application method count below 64K if you have not yet.

**Comment by nabeelpkl** [comment]
@dbrgn this was the same issue I had. now running without using multidex. methods exceeded when I imported the whole google playservices.

**Comment by dbrgn** [comment]
So to avoid using multidex, do you enable ProGuard and the `minifyEnabled` flag even in debug mode?

**Comment by nabeelpkl** [comment]
see the [link](http://stackoverflow.com/a/37003814/1769274). thats how I solved the issue.

**Comment by kaneelyster** [comment]
I've been battling this pre-Lollipop crashing for a few days and found a way to make multidex and sqlcipher 3.5.4 play along. Getting rid of multidex via method count reduction wasn't a practical solution for us (looking at you bloaty Facebook SDK).

My best stab at explaining the crash is that the sqlcipher native libs (and/or classes) don't get pulled into the first dex when you're breaching the 64K limit, resulting in the crashing when calling `SQLiteDatabase.loadLibs(context)` from my content provider.

Solution:
In build.gradle, point to a multiDexKeepFile:  
```gradle
// Enabling multidex support. 
multiDexEnabled true 
multiDexKeepFile file('multidex.keep')
```

And in the keep file, specify the classes you need to be included in the first dex, in my case my content provider and sqlcipher's SQLiteDatabase: 
```
com/myapp/android/database/provider/MyContentProvider.class
net/sqlcipher/database/SQLiteDatabase.class
```

This stopped the crashing from happening on both a physical S3 mini and a nexus 4 virtual device (both api 16, both crashed before the fix).

**Comment by developernotes** [comment]
Hi @kaneelyster 

Thank you for sharing your solution for others!

**Comment by dbrgn** [comment]
The solution above didn't work out for me, but going with the proguard syntax helped:

```
// // Enabling multidex support. 
multiDexEnabled true 
multiDexKeepProguard file('multidex-keep.pro')
```

And the keep file `multidex-keep.pro`:

```
-keep public class net.sqlcipher.** { *; }
-keep public class org.your.app.** { *; }
```
