### ISSUE TITLE
Cannot create nonexistent database file when executing ATTACH to decrypt database

### ISSUE THREAD

**Issue by perqin** [sqlcipher/android-database-sqlcipher#259]
I am trying to decrypt a database file with passphrase:
```
SQLiteDatabase.loadLibs(myApp.appContext);
SQLiteDatabase database = SQLiteDatabase.openDatabase(srcFile.getAbsolutePath(), password, null, SQLiteDatabase.OPEN_READWRITE, new EnMicroMsgHook());
database.rawExecSQL(String.format("ATTACH DATABASE '%s' AS decrypted_database KEY ''", destFile.getAbsolutePath()));
database.rawExecSQL("SELECT sqlcipher_export('decrypted_database')");
database.rawExecSQL("DETACH DATABASE decrypted_database");
```
, where the `destFile` does not exist. Then I get such log:
```
I/Database: JNI_OnLoad called
I/Database: JNI_OnLoad register methods 
I/Database: sqlite returned: error code = 14, msg = cannot open file at line 36774 of [3d862f207e]
I/Database: sqlite returned: error code = 14, msg = os_unix.c:36774: (2) open(/storage/sdcard0/MyApp/newdir/EnMicroMsg.db) - 
I/Database: sqlite returned: error code = 14, msg = statement aborts at 5: [ATTACH DATABASE '/storage/sdcard0/MyApp/newdir/EnMicroMsg.db' AS decrypted_database KEY ''] unable to open database: /storage/sdcard0/MyApp/newdir/EnMicroMsg.db
```
and this error was thrown at `database.rawExecSQL(String.format("ATTACH DATABASE '%s' AS decrypted_database KEY ''", destFile.getAbsolutePath()));`

Then I went to the destination directory, create an empty file `EnMicroMsg.db`, rerun the app, and everything works well.

The SQL commands above works on my Ubuntu with SqlCipher 3.7, so should it be considered a bug?

**Comment by developernotes** [comment]
Hi @perqin 

Can you try running the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? We include a [test](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/src/main/java/net/zetetic/tests/ExportToUnencryptedDatabase.java) that performs an export to a plain text database file that does not exist which appears to be what you are attempting.

**Comment by perqin** [comment]
@developernotes I tried running the test on my Android device. Though all 62 tests are passed, I notice an error in log:
```
09-15 04:05:08.632 8111-8683/net.zetetic E/Database: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
                                                     net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
                                                         at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
                                                         at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
                                                         at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
                                                         at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
                                                         at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
                                                         at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
                                                         at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1787)
                                                         at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1752)
                                                         at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2427)
                                                         at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2356)
                                                         at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1116)
                                                         at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1056)
                                                         at net.zetetic.tests.MUTF8ToUTF8WithNullMigrationTest.execute(MUTF8ToUTF8WithNullMigrationTest.java:36)
                                                         at net.zetetic.tests.SQLCipherTest.run(SQLCipherTest.java:36)
                                                         at net.zetetic.tests.TestSuiteRunner.runSuite(TestSuiteRunner.java:40)
                                                         at net.zetetic.tests.TestSuiteRunner.doInBackground(TestSuiteRunner.java:20)
                                                         at net.zetetic.tests.TestSuiteRunner.doInBackground(TestSuiteRunner.java:12)
                                                         at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                         at java.lang.Thread.run(Thread.java:818)
```

**Comment by developernotes** [comment]
Hello @perqin 

The log line you identified in the `MUTF8ToUTF8WithNullMigrationTest` test is expected as the source database in that test was created with a password encoded using modified UTF-8. The initial step is to encode the key material using UTF-8 which causes the query to `sqlite_master` to fail, the library handles that exception, attempts to key the database using modified UTF-8 and if successful via a query to `sqlite_master`, rekeys the database using UTF-8.

Have you verified the directory structure exists for your attach path? Have you tried an alternative path?

**Comment by perqin** [comment]
@developernotes Yes, I've verified the structure. Also I change the parent directory to sd card(/storage/sdcard0/En.db) but also failed. The current workaround is to create an empty destination file before executing the sql commands.

**Comment by perqin** [comment]
@developernotes I read the test case and its commands are identical to mine. I then remove the hook and use an unencrypted database file as source but it still tells me that it cannot open destination file.

**Comment by perqin** [comment]
@developernotes I guess I know the cause.
```
SQLiteDatabase database = SQLiteDatabase.openOrCreateDatabase("/storage/sdcard0/test.db", "why", null);  // #1
SQLiteDatabase database = SQLiteDatabase.openDatabase("/storage/sdcard0/test.db", "why", null, SQLiteDatabase.OPEN_READWRITE);  // #2
```
In the above code, I use two statements respectively, in both tests I've verified that test.db exists and the file to be attached doesn't exist. The first statement passes while the second one fails.
So I dig into the source and find that I must use the flag `CREATE_IF_NECESSARY` instead of `OPEN_READWRITE`! So the flags are applied to all the involved databases instead of the one that opened using 'SQLiteDatabase.openDatabase()`. Thanks for your patient help!

**Comment by developernotes** [comment]
Hello @perqin 

I'm glad to hear that everything is working well for you now, take care!
