### ISSUE TITLE
SQLCipher does not load down the .so files for arm64/32-v8 devices

### ISSUE THREAD

**Issue by CCorrado** [sqlcipher/android-database-sqlcipher#261]
Hi all,

When compiling this lib on a device with the arm32/64-v8 chip architecture (Snapdragon 810/820, exynos 8890) i.e. the Note 7 or some of the other latest devices, the build cannot find the .so files needed to compile.

`09-23 09:23:27.992 31531-31531/? E/Zygote: v2
09-23 09:23:27.992 31531-31531/? E/Zygote: accessInfo : 0
09-23 09:23:28.092 31531-31531/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.*.*.*.qa, PID: 31531
                                                   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.*.*.*.qa-2/base.apk"],nativeLibraryDirectories=[/data/app/com.*.*.*.qa-2/lib/arm64, /data/app/com.*.*.*.qa-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libsqlcipher.so"
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                       at java.lang.System.loadLibrary(System.java:1076)
                                                       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:196)
                                                       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:189)
                                                       at com.*.*.*.CareAppProduction.onCreate(SourceFile:17)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6428)
                                                       at android.app.ActivityThread.access$1800(ActivityThread.java:229)
`

**Comment by developernotes** [comment]
Hi @CCorrado 

SQLCipher for Android does not currently include 64-bit native libraries, however it will work on 64-bit devices. Please see [these](https://discuss.zetetic.net/t/sqlcipher-for-android-native-library-support/1440) instructions for further details.

**Comment by CCorrado** [comment]
Thanks!
