### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4"

### ISSUE THREAD

**Issue by ulx** [sqlcipher/android-database-sqlcipher#263]
I have problem this lib.
I use nexus 7 (2013 year) Android OS - 6 
  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4" referenced by "/data/app/ru.raiffeisen.rmobile-1/lib/arm/libsqlcipher.so"...
                                                                           at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                           at java.lang.System.loadLibrary(System.java:1076)
                                                                           at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:196)
                                                                           at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:189)

**Comment by developernotes** [comment]
Hi @ulx 

Are you using the Community edition binaries of SQLCipher for Android, or did you build the library yourself? What version of SQLCipher are you using?

**Comment by ulx** [comment]
I using version 3.5.4
I builded the library.

**Comment by developernotes** [comment]
Hi @ulx 

You might consider trying the [community edition build](https://www.zetetic.net/sqlcipher/sqlcipher-for-android/) of the library. It may be due to the NDK version you have used, we have some guidance on building from source [here](https://github.com/sqlcipher/android-database-sqlcipher#building).

**Comment by ulx** [comment]
I using NDK version compile 12.1.2977

**Comment by xiaviv** [comment]
targetSdkVersion 要和ndk支持的版本一致，你可以提高targetSdkVersion版本或使用低版本的ndk

targetSdkVersion must be consistent with the ndk support version, you may enhance the targetSdkVersion version or use the
