### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by CreacionesJA** [sqlcipher/android-database-sqlcipher#268]
Hello, lately since upgrade to version 3.5.4 on different devices using Android 4.x, 5.x and 6.x the following exception occurs:

Edit: Added line numbers in the trace exception:

```
Fatal Exception: java.lang.UnsatisfiedLinkError: Native method not found: net.sqlcipher.database.SQLiteDatabase.dbopen:(Ljava/lang/String;I)V
       at net.sqlcipher.database.SQLiteDatabase.dbopen(SQLiteDatabase.java)
       at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2353)
       at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1116)
       at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1083)
       at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1032)
       at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:986)
       at com.ijsoft.gpul.Util.SQLiteAssets.SQLiteCipherAssetHelper.returnDatabase(SQLiteCipherAssetHelper.java:423)
       at com.ijsoft.gpul.Util.SQLiteAssets.SQLiteCipherAssetHelper.createOrOpenDatabase(SQLiteCipherAssetHelper.java:399)
       at com.ijsoft.gpul.Util.SQLiteAssets.SQLiteCipherAssetHelper.getWritableDatabase(SQLiteCipherAssetHelper.java:186)
       at com.ijsoft.gpul.Util.SQLiteAssets.SQLiteCipherAssetHelper.getReadableDatabase(SQLiteCipherAssetHelper.java:264)
       at com.ijsoft.gpul.Util.DbMainFunctions.openDatabase(DbMainFunctions.java:38)
       at com.ijsoft.gpul.MainActivity.onResume(MainActivity.java:473)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
       at android.app.Activity.performResume(Activity.java:5211)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2780)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2266)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5103)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)

```

It occurs in some ARMv7, ARMv8 and x86 devices.

Sorry for my bad English.

**Comment by developernotes** [comment]
Hi @CreacionesJA 

There are a couple of possibilities based on your stack trace, here are a few follow up questions:

1. Are you using ProGuard?
2. Are you using other third-party libraries that include native dependencies?

If you are using ProGuard, you might consider looking at our [sample](https://github.com/sqlcipher/android-database-sqlcipher/blob/v3.4.0/proguard-project.txt). If you are including other third-party libraries that have native dependencies bundled, you might find [this](https://discuss.zetetic.net/t/sqlcipher-for-android-native-library-support/1440) helpful regarding interoperability.

**Comment by CreacionesJA** [comment]
Yes, I use ProGuard, and do not use any additional native library.

ProGuard file:

```
-keep class net.sqlcipher.** {
    *;
}
-keep class android.support.** {
    *;
}
-keepattributes EnclosingMethod
```

**Comment by developernotes** [comment]
Hi @CreacionesJA 

Were you able to resolve the crash behavior? Have you tried utilizing our ProGuard file referenced above?

**Comment by CreacionesJA** [comment]
I've already solved the problem. It was not correctly initialized the library (SQLiteDatabase.loadLibs (this)) in one of the activities of my application.

**Comment by developernotes** [comment]
Hi @CreacionesJA,

Thank you for the quick response, I'm glad to hear the issue has been resolved. Take care!

**Comment by mehtaketan7** [comment]
@iJRSoftware how you resolved an issue for (SQLiteDatabase.loadLibs (this)) for this?
