### ISSUE TITLE
net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;

### ISSUE THREAD

**Issue by meetsagarlandge25** [sqlcipher/android-database-sqlcipher#273]
I have done db encryption using SQLcipher . Now I am checking the upgrade scenario wherein i am trying to update my previous version of my app whose db is not encrypted with the current version which has encrypted db . I am getting the following error on launch of the app - 

 Caused by: net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
 at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
 at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
 at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
 at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1787)
at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1752)
at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2427)
at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2356)
at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1116)
at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1008)
 at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:249)
 at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:214)

**Comment by developernotes** [comment]
Hi @meetsagarlandge25 

It is difficult to say why you are receiving that stack trace without a posting of the code that is executing. You may find [this](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/src/main/java/net/zetetic/tests/ImportUnencryptedDatabaseTest.java) test helpful as it shows the process for importing a plain text database into an encrypted database.

**Comment by meetsagarlandge25** [comment]
This is my onCreate() of ContentProvider class:  

public void onCreate()
   {
      SQLiteDatabase.loadLibs(getContext());
      mOpenHelper = new DBHelper(getContext());
      try {
         encrypt(getContext(),DATABASE_NAME,pass);
      } catch (IOException e) {
         e.printStackTrace();
      }
   }

This is my encrypt method:
public static void encrypt(Context ctxt, String dbName,String passphrase) throws IOException {
      File originalFile=ctxt.getDatabasePath(dbName);
    
      if (originalFile.exists()) {
         File newFile=File.createTempFile("sqlcipherutils", "tmp",ctxt.getCacheDir());
         SQLiteDatabase db = SQLiteDatabase.openDatabase(originalFile.getAbsolutePath(),"", null,
                             SQLiteDatabase.OPEN_READWRITE);
         db.rawExecSQL(String.format("ATTACH DATABASE '%s' AS encrypted KEY '%s';",
                 newFile.getAbsolutePath(), passphrase));
         db.rawExecSQL("SELECT sqlcipher_export('encrypted')");
         db.rawExecSQL("DETACH DATABASE encrypted;");
         int version=db.getVersion();
         db.close();
         db=SQLiteDatabase.openDatabase(newFile.getAbsolutePath(),passphrase, null,
                         SQLiteDatabase.OPEN_READWRITE);
         db.setVersion(version);
         db.close();

         originalFile.delete();
         newFile.renameTo(originalFile);
      }
   }

When i update my previous UNENCRYTED db with new ENCRYPTED db its working as expected . Note, my db version is the same for both .

I am facing issue when i try to update app whose db is now ENCRYPTED with the new version of app. Following is the error : 

Caused by: net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1787)
at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1752)
at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2427)
at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2356)
at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1116)
at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1083)
  at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1032)
  at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:986)
  **at com.xxxxxxxxxxxxxx.Provider.encrypt(Provider.java:98)
  at com.xxxxxxxxxxxxxx.Provider.onCreate(Provider.java:84)**
  at android.content.ContentProvider.attachInfo(ContentProvider.java:1656)
  at android.content.ContentProvider.attachInfo(ContentProvider.java:1627)
    at android.app.ActivityThread.installProvider(ActivityThread.java:5015)
 at android.app.ActivityThread.installContentProviders(ActivityThread.java:4589) 
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4522) 
     at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381) 
   at android.os.Handler.dispatchMessage(Handler.java:110) 
   at android.os.Looper.loop(Looper.java:193) 
    at android.app.ActivityThread.main(ActivityThread.java:5299) 
  at java.lang.reflect.Method.invokeNative(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:515) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641) 
   at dalvik.system.NativeStart.main(Native Method) 

It is throwing error at SQLiteDatabase db = SQLiteDatabase.openDatabase(originalFile.getAbsolutePath(),"", null,                       SQLiteDatabase.OPEN_READWRITE);

where I am trying to open the encryted db by passing "" and if I pass the passphrase into it then the normal upgradation with fail(unencrypted db to encryted db update) . Please suggest what should be done .

**Comment by developernotes** [comment]
Hi @meetsagarlandge25 

>When i update my previous UNENCRYTED db with new ENCRYPTED db its working as expected . Note, my db version is the same for both .

This is good news. If `originalFile` references the unencrypted database, you will only be able to open it with an empty password (i.e., `""`), however if it is encrypted you will only be able to open it with the password used when your performed the `sqlcipher_export(…)` process. Maybe you could utilize a different filename to keep track of whether you have performed the upgrade process.

**Comment by theBlbDan** [comment]
@meetsagarlandge25 
Your onCreate() assumes the file is plain text every time it is run.  You're not doing anything about the case where it is already encrypted.

This is an example of my open method in my DataBaseHelper class.  Because I have a mixture of encrypted and plain DB's, I simply test the beginning of the file to determine what I'm working with.  You could do the same, and then process it for encryption.

```java
private void openDb() {
    if(db != null && db.isOpen()) { return; }
    synchronized (myActivity.sDataLock) {
        try {
            String s = "SQLite format 3";
            byte[] b = new byte[s.length()];
            final int bytesRead = FileUtils.openInputStream(new File(DATABASE_PATH)).read(b);
            if(bytesRead == s.length() && s.equals(new String(b))) {
                // Not an encrypted DB
            } else {
                // DB is encrypted?
            }
        } catch (IOException e) { }
    }
}
```

**Comment by malik082009** [comment]
I was getting this exception only in obfuscation case. 

I added default constructors for both `ByteArraySerializer` and `ByteArrayDeserializer` classes.

Note: don't add above classes as inner classes. Declare these classes independently add `keep` these classes in `proguard-rules`.
