### ISSUE TITLE
SQLiteException database is locked:BEGIN EXCLUSIVE

### ISSUE THREAD

**Issue by carson123** [sqlcipher/android-database-sqlcipher#278]
i have a crash log on 3.5.4  as follows
Caused by :net.sqlcipher.database.SQLiteException:database is locked:BEGIN EXCLUSIVE;
net.sqlcipher.database.SQLiteDatabase.native_execSQL
net.sqlcipher.database.SQLiteDatabase.execSQL
net.sqlcipher.databaseSQLiteDatabase.beginTransacionWithListener
net.sqlcipher.database.SQLiteDatabase.beginTransaction

**Comment by developernotes** [comment]
Hi @carson123 

Are you able to consistently reproduce the issue? If so, we would be happy to look into it further if you can create a test case within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests). Thanks!

**Comment by zhugscn** [comment]
We have met the same problem 

My code have include a synchronization mechanism when it read/write database in multi-threaded environment.

gradle version:3.4
Android studio version:2.3

The key info of build.gradle file is as follows:
android {
compileSdkVersion 25
buildToolsVersion "25.0.2"
useLibrary 'org.apache.http.legacy'

defaultConfig {
    //dex 65535
    multiDexEnabled true
}
The crash log is as follows:

java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: net.sqlcipher.database.SQLiteException: database is locked: BEGIN EXCLUSIVE;
at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
at net.sqlcipher.database.SQLiteDatabase.beginTransactionWithListener(SQLiteDatabase.java:706)
at net.sqlcipher.database.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:658)
at com.pos.xwpos.db.DBFactory.saveroleRightGroup(DBFactory.java:4959)
at com.pos.xwpos.task.GetMerrightsetsTask.doInBackground(GetMerrightsetsTask.java:133)
at com.pos.xwpos.task.GetMerrightsetsTask.doInBackground(GetMerrightsetsTask.java:36)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
net.sqlcipher.database.SQLiteException: database is locked: BEGIN EXCLUSIVE;
at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
at net.sqlcipher.database.SQLiteDatabase.beginTransactionWithListener(SQLiteDatabase.java:706)
at net.sqlcipher.database.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:658)
at com.pos.xwpos.db.DBFactory.saveroleRightGroup(DBFactory.java:4959)
at com.pos.xwpos.task.GetMerrightsetsTask.doInBackground(GetMerrightsetsTask.java:133)
at com.pos.xwpos.task.GetMerrightsetsTask.doInBackground(GetMerrightsetsTask.java:36)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

**Comment by developernotes** [comment]
Hello @carson123, @zhugscn 

Are you just calling `database.beginTransaction()` after opening the database? I tried running that within the [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) and did not receive an error. Any additional information you can share regarding the issue would be beneficial.

**Comment by zyh9018** [comment]
Hello @developernotes ,
   My app met this exception more than 50 times. The device version from 4.1.1 to 5.0.1.
it caused when doint executeInsert() in an transaction.
Is there any clues that may cause this?
Any help will be appreciated. Thanks.

**Comment by developernotes** [comment]
Hi @zyh9018 

Can you please answer the questions posted [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/278#issuecomment-291161874). Additional information will be helpful in diagnosing the issue.

**Comment by developernotes** [comment]
Hello @carson123, @zyh9018 

Are you still experiencing an issue? If so, are you able to reproduce the error within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by developernotes** [comment]
Hello @carson123, @zyh9018

Since we have not heard back, I am going to close this ticket. If you still experiencing an issue we would be happy to investigate this further. Please fee free to open a new ticket and provide supporting information regarding your issue, preferably with a reproducible test case within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests). Thanks!
