### ISSUE TITLE
File is encrypted or is not a database

### ISSUE THREAD

**Issue by jordanterry** [sqlcipher/android-database-sqlcipher#281]
Hello,

I am currently upgrading the version of SQLCipher, within an app I am working on, to version 3.5.4. Since upgrading I have run into issues whilst upgrading the app from an older version that uses the older library.

When I upgrade the app I get the following error:

```
E/Database: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
  net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
  at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
  at net.sqlcipher.database.SQLiteCompiledSql.compile(SourceFile:91)
  at net.sqlcipher.database.SQLiteCompiledSql.<init>(SourceFile:64)
  at net.sqlcipher.database.SQLiteProgram.<init>(SourceFile:83)
  at net.sqlcipher.database.SQLiteQuery.<init>(SourceFile:49)
  at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SourceFile:42)
  at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SourceFile:1785)
  at net.sqlcipher.database.SQLiteDatabase.rawQuery(SourceFile:1750)
  at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SourceFile:2404)
  at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SourceFile:2333)
  at net.sqlcipher.database.SQLiteDatabase.openDatabase(SourceFile:1114)
  at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SourceFile:1177)
  at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SourceFile:162)
  at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SourceFile:227)
  at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SourceFile:214)
  at app.package.sqlite.DatabaseHelperVanguard.getReadableDatabase(SourceFile:188)
  at app.package.Application.onCreate(SourceFile:51)
  at app.package.Application.onCreate(Application.java:36)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
  at android.app.ActivityThread.-wrap2(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6077)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
E/SQLiteOpenHelper: Couldn't open database.db for writing (will try read-only):
  net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
  at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
  at net.sqlcipher.database.SQLiteCompiledSql.compile(SourceFile:91)
  at net.sqlcipher.database.SQLiteCompiledSql.<init>(SourceFile:64)
  at net.sqlcipher.database.SQLiteProgram.<init>(SourceFile:83)
  at net.sqlcipher.database.SQLiteQuery.<init>(SourceFile:49)
  at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SourceFile:42)
  at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SourceFile:1785)
  at net.sqlcipher.database.SQLiteDatabase.rawQuery(SourceFile:1750)
  at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SourceFile:2404)
  at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SourceFile:2333)
  at net.sqlcipher.database.SQLiteDatabase.openDatabase(SourceFile:1114)
  at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SourceFile:1177)
  at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SourceFile:162)
  at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SourceFile:227)
  at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SourceFile:214)
  at app.package.sqlite.DatabaseHelperVanguard.getReadableDatabase(SourceFile:188)
  at app.package.Application.onCreate(SourceFile:51)
  at app.package.Application.onCreate(Application.java:36)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
  at android.app.ActivityThread.-wrap2(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6077)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
E/Database: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
  net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
  at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
  at net.sqlcipher.database.SQLiteCompiledSql.compile(SourceFile:91)
  at net.sqlcipher.database.SQLiteCompiledSql.<init>(SourceFile:64)
  at net.sqlcipher.database.SQLiteProgram.<init>(SourceFile:83)
  at net.sqlcipher.database.SQLiteQuery.<init>(SourceFile:49)
  at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SourceFile:42)
  at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SourceFile:1785)
  at net.sqlcipher.database.SQLiteDatabase.rawQuery(SourceFile:1750)
  at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SourceFile:2404)
  at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SourceFile:2333)
  at net.sqlcipher.database.SQLiteDatabase.openDatabase(SourceFile:1114)
  at net.sqlcipher.database.SQLiteDatabase.openDatabase(SourceFile:1006)
  at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SourceFile:249)
  at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SourceFile:214)
  at app.package.sqlite.DatabaseHelperVanguard.getReadableDatabase(SourceFile:188)
  at app.package.Application.onCreate(SourceFile:51)
  at app.package.Application.onCreate(Application.java:36)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
  at android.app.ActivityThread.-wrap2(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6077)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

One piece of information I am missing is the version of SQLCipher I was using previously. There is no information telling me what was used before I have upgraded. Is there anyway I can work out the version from the old jar?

Can you offer any advice on fixing this issue?

**Comment by theBlbDan** [comment]
You can execute [PRAGMA cipher_version](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_version) to determine which version you are / were running.  If you are migrating form 2.x to 3x, you will need to execute [PRAGMA cipher_migrate](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate).

**Comment by jordanterry** [comment]
Thanks for your help! Problem solved.
