### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by nachtien** [sqlcipher/android-database-sqlcipher#282]
Hi there!

I'm trying to track down a crash that occurred in our app (this came in through Crashlytics).  This enters through sqlcipher, and somehow gets passed through XPrivacy, which a Google search shows it as being an xposed module.  Does anyone have any insight as to why this crash occurred?

Thanks

Fatal Exception: java.lang.UnsatisfiedLinkError: XPrivacy
       at biz.bokhorst.xprivacy.XRuntime.a(SourceFile:81)
       at biz.bokhorst.xprivacy.XPrivacy$XMethodHook.beforeHookedMethod(SourceFile:628)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:661)
       at java.lang.Runtime.loadLibrary(<Xposed>)
       at java.lang.System.loadLibrary(System.java:1076)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:196)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:189)
       at com.pax.app.data.database.Database.<init>(Database.java:54)
       at com.pax.app.data.database.Database.get(Database.java:45)
       at com.pax.app.data.database.Database.getCursor(Database.java:84)
       at com.pax.app.data.database.Database.getPeripherals(Database.java:89)
       at com.pax.app.ui.fragment.SplashFragment$3$1.run(SplashFragment.java:82)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)

**Comment by developernotes** [comment]
Hi @nachtien 

SQLCipher for Android does not utilize XPrivacy. It appears that XPrivacy throws an unsatisfied link error exception when `loadLibrary()` is called, which SQLCipher for Android does need to perform. Unfortunately, there is not anything we can do about this, you might try reaching out to your customer.

[1] https://github.com/M66B/XPrivacy#restrictions
