### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by wobuaihuangjun** [sqlcipher/android-database-sqlcipher#284]
i have a crash log as follows
Caused by: net.sqlcipher.database.SQLiteException: error code 14: unable to open database file
	at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
	at net.sqlcipher.database.SQLiteStatement.execute(Unknown Source)
	at net.sqlcipher.database.SQLiteDatabase.execSQL(Unknown Source)
	at com.j256.ormlite.sqlcipher.android.AndroidCompiledStatement.execSql(Unknown Source)
	at com.j256.ormlite.sqlcipher.android.AndroidCompiledStatement.runUpdate(Unknown Source)
	at com.j256.ormlite.stmt.StatementExecutor.delete(Unknown Source)
	at com.j256.ormlite.dao.BaseDaoImpl.delete(Unknown Source)
	at com.j256.ormlite.stmt.DeleteBuilder.delete(Unknown Source)

**Comment by developernotes** [comment]
Hi @wobuaihuangjun 

Can you provide some additional details on the SQL operating that was occurring when the error occurred? Are you able to reproduce the issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? Thanks!

**Comment by hak-tpl** [comment]
same crashed occurred to me on android 7.0

**Comment by developernotes** [comment]
Hi @hak-tpl 

Can you provide some additional details on the query being performed when you receive the error? Are you able to reproduce the error using the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? Does the crash occur on a device, or emulator?

**Comment by hak-tpl** [comment]
@developernotes 

I'm unable to reproduce this crash as this crash was reported by an anonymous user of my app. However this crash occurred when `db.update() `query was called.

```
STACK_TRACE=net.sqlcipher.database.SQLiteException: error code 14: unable to open database file
at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
at net.sqlcipher.database.SQLiteStatement.a(SQLiteStatement.java:58)
at net.sqlcipher.database.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:2134)
at net.sqlcipher.database.SQLiteDatabase.update(SQLiteDatabase.java:2060)
```

**Comment by developernotes** [comment]
Hi @hak-tpl 

What device did it occur on? What version of SQLCipher for Android are you using?

**Comment by hak-tpl** [comment]
@developernotes 

DEice was ONEPLUS A3010 running Android v7.0. And I'm using dependency v3.5.3

**Comment by developernotes** [comment]
Hi @hak-tpl 

Please try using the latest version, 3.5.6 and let us know if you continue to experience the behavior. Thanks!

**Comment by developernotes** [comment]
Hi @wobuaihuangjun

Are you able to provide additional details on the SQL operating that was occurring when the error occurred? Are you able to reproduce the issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by jcb316733855** [comment]
My online App have the same crash,The User's Device is Samsung SM-J3109。i can't reproduce this issue, this log is collected by our log server, please help me, thanks。
net.sqlcipher.database.SQLiteException: error code 14: unable to open database file
	at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
	at net.sqlcipher.database.SQLiteStatement.execute(SQLiteStatement.java:58)
	at net.sqlcipher.database.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:2149)
	at net.sqlcipher.database.SQLiteDatabase.update(SQLiteDatabase.java:2075)

**Comment by developernotes** [comment]
Hi @jcb316733855 

What version of SQLCipher for Android are you using?

**Comment by jcb316733855** [comment]
the version is 3.5.4

**Comment by developernotes** [comment]
Hello @jcb316733855 

I have commented separate on your open ticket.
