### ISSUE TITLE
UnsatisfiedLinkError:

### ISSUE THREAD

**Issue by wangjing53406** [sqlcipher/android-database-sqlcipher#288]
java.lang.UnsatisfiedLinkError: dlopen failed: library "V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~`V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c݄(~3-V䌒c
       at java.lang.Runtime.loadLibrary(Runtime.java:371)
       at java.lang.System.loadLibrary(System.java:988)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:196)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:189)
       at org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper.(SourceFile:174)
       at org.greenrobot.greendao.database.DatabaseOpenHelper.checkEncryptedHelper(SourceFile:121)
       at org.greenrobot.greendao.database.DatabaseOpenHelper.getEncryptedWritableDb(SourceFile:133)
       at com.culiu.imlib.core.db.DaoSessionHelper.getDaoMaster(SourceFile:49)
       at com.culiu.imlib.core.db.DaoSessionHelper.getDaoSession(SourceFile:73)

I use sqlcipher with greendao, most of this problem in android 4.2.2, 4.4.4

**Comment by developernotes** [comment]
Hello @wangjing53406 

I am not sure what characters are being printed following the dlopen failed: library: block. You might want to make sure greenDAO is utilizing the latest SQLCipher for Android library. Alternatively, I would recommend reporting your error to their Github issue page [here](https://github.com/greenrobot/greenDAO/issues/new).
