### ISSUE TITLE
Getting random crashes "Couldn't open db for writing (will try to read only)  net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;"

### ISSUE THREAD

**Issue by RaduPopescu29** [sqlcipher/android-database-sqlcipher#290]
I am using a ContentProvider with cipher.SQLiteOpenHelper and CursorLoaders to display data. 
In the ContentProvider onCreate method I have  SQLiteDatabase.loadLibs(getContext()). In the query method ot he ContentProvider i have 
  final SQLiteDatabase db = database.getReadableDatabase(password); which gives this error:

file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
                                                                          net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;

I am using a CursorLoader to query data. This does not happen all the time. With a fresh install everything works well, but when I reopen the app I constantly gets this crash.

I am using  net.zetetic:android-database-sqlcipher:3.5.4@aar, Android version 6.0.1.

Any ideas?

**Comment by developernotes** [comment]
Hello @RaduPopescu29,

Is this something you are able to reproduce within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? Are you certain you are always providing the correct password when you call `getReadableDatabase(…);`?

**Comment by SameerMB** [comment]
I did observed the same error on Samsung S7, Android 6.0.1.
Crash was on upgrading the app & it happened sometimes only.

**Comment by nkmadala** [comment]
I'm also observing the same issue randomly on HTC one, Android 6.0 with the following log. Any help or update on the issue please?

`

```
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
02-15 10:21:22.105 15591-15591/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.qumu.viewer, PID: 15591
                                                   net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
                                                       at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
                                                       at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
                                                       at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
                                                       at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
                                                       at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
                                                       at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
                                                       at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1787)
                                                       at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1752)
                                                       at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2427)
                                                       at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2356)
                                                       at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1116)
                                                       at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1179)
                                                       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
                                                       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:129)
```

`

**Comment by developernotes** [comment]
Hi @SameerMB, @nkmadala,

Can you run the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? Can you confirm that you are always providing the same password to `getReadableDatabase(…);`?
