### ISSUE TITLE
throw net.sqlcipher.database.SQLiteException: attempt to write a readonly database: , while compiling: select count(*) from sqlite_master; when I open readOnly.

### ISSUE THREAD

**Issue by huhuang03** [sqlcipher/android-database-sqlcipher#299]
Throw an exception:
```
E/Database: attempt to write a readonly database: , while compiling: select count(*) from sqlite_master;
    net.sqlcipher.database.SQLiteException: attempt to write a readonly database: , while compiling: select count(*) from sqlite_master;
	at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
	at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
	at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
	at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
	at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1787)
	at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1752)
	at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2427)
	at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2356)
	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1116)
	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1083)
	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1032)

```

I use this in my `build.gradle`  `compile 'net.zetetic:android-database-sqlcipher:3.5.4@aar'
`
And I open as readonly:

```
db = SQLiteDatabase.openDatabase(mDbFile.getAbsolutePath(), mPassword, null, SQLiteDatabase.OPEN_READONLY, mHook);
                    String sql = "select * from userinfo";
                    c = db.rawQuery(sql, null);
```

myHook:
```
mHook = new SQLiteDatabaseHook() {
    public void preKey(SQLiteDatabase database) {
    }

    public void postKey(SQLiteDatabase database) {
	database.rawExecSQL("PRAGMA cipher_migrate;");
    }
};
```

**Comment by alphatydeus** [comment]
Yes, I also got a similar error and deleting the related -journal file solved the issue. I think the database was force closed and it didn't delete the -journal file
