### ISSUE TITLE
Native crash on Android 4.1.2

### ISSUE THREAD

**Issue by antoxa2584x** [sqlcipher/android-database-sqlcipher#304]
Nexus S 4g - 4.1.2
```
FATAL EXCEPTION: main
java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1306]:    88 cannot locate 'signal'...
    at java.lang.Runtime.loadLibrary(Runtime.java:370)
    at java.lang.System.loadLibrary(System.java:535)
    at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:195)
    at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:188)
    at com.activeandroid.app.ActiveAndroidSecureApplication.attachBaseContext(ActiveAndroidSecureApplication.java:43)
    at android.app.Application.attach(Application.java:146)
    at android.app.Instrumentation.newApplication(Instrumentation.java:983)
    at android.app.Instrumentation.newApplication(Instrumentation.java:967)
    at android.app.LoadedApk.makeApplication(LoadedApk.java:496)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4124)
    at android.app.ActivityThread.access$1300(ActivityThread.java:130)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4745)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by developernotes** [comment]
Hello @antoxa2584x 

This issue was resolved in 3.5.6, would you try that build and let us know your results? Thanks!

**Comment by antoxa2584x** [comment]
@developernotes, yep. 3.5.6 work fine

**Comment by developernotes** [comment]
Hi @antoxa2584x 

Great, glad to hear that addressed the issue. Thanks!
