### ISSUE TITLE
database is locked: BEGIN EXCLUSIVE on three different android 5.1.1 devices

### ISSUE THREAD

**Issue by zhugscn** [sqlcipher/android-database-sqlcipher#326]
We have met the same problem on 3 different android 5.1.1 devices (3 android4.4 devices, 2 android 5.1 devices, and 1 6.0 devices seems okay).

I use the latest version of sqlcipher for android.

My code have include a synchronization mechanism when it read/write database in multi-threaded environment.

And we do not close database everytime, because we found that open database cost too much time(about 900ms )

gradle version:3.4
Android studio version:2.3

The key info of build.gradle file is as follows:
android {
compileSdkVersion 25
buildToolsVersion "25.0.2"
useLibrary 'org.apache.http.legacy'

defaultConfig {
//dex 65535
multiDexEnabled true
}
The crash log is as follows:

java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: net.sqlcipher.database.SQLiteException: database is locked: BEGIN EXCLUSIVE;
at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
at net.sqlcipher.database.SQLiteDatabase.beginTransactionWithListener(SQLiteDatabase.java:706)
at net.sqlcipher.database.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:658)
at com.pos.xwpos.db.DBFactory.saveroleRightGroup(DBFactory.java:4959)
at com.pos.xwpos.task.GetMerrightsetsTask.doInBackground(GetMerrightsetsTask.java:133)
at com.pos.xwpos.task.GetMerrightsetsTask.doInBackground(GetMerrightsetsTask.java:36)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
net.sqlcipher.database.SQLiteException: database is locked: BEGIN EXCLUSIVE;
at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
at net.sqlcipher.database.SQLiteDatabase.beginTransactionWithListener(SQLiteDatabase.java:706)
at net.sqlcipher.database.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:658)
at com.pos.xwpos.db.DBFactory.saveroleRightGroup(DBFactory.java:4959)
at com.pos.xwpos.task.GetMerrightsetsTask.doInBackground(GetMerrightsetsTask.java:133)
at com.pos.xwpos.task.GetMerrightsetsTask.doInBackground(GetMerrightsetsTask.java:36)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

**Comment by zhugscn** [comment]
with oracle jdk1.8.0_121

**Comment by developernotes** [comment]
Hello @zhugscn 

A few follow up questions:

- What are the specific devices you receive the error on?
- Does the error occur immediately following opening the database with a key?

**Comment by developernotes** [comment]
Hello @zhugscn,

We have pushed a change to master that we believe may address the crash when loading large data sets. Would you be interested in trying a beta build? If so, please reach out to us at [support@zetetic.net](mailto:support@zetetic.net). Thanks!

**Comment by zhugscn** [comment]
Thank you , Nick Parker.

1. What are the specific devices you receive the error on? 
  --- our android devices are all custom devices for commercial usage, with different CPUs(e.g. one use Qualcomm MSM8909, the other one is )
2. Does the error occur immediately following opening the database with a key?
  ---No. wen use only ONE insance:  mDatabase = mDatabaseHelper.getWritableDatabase("keykeykey");
      the error occur when we call : 
        SQLiteDatabase db = CustomDBHelper.mDatabaseManager.getWritableDatabase();
        db.beginTransaction();

**Comment by zhugscn** [comment]
And I have mailed to support@zetetic.net, thanks.

**Comment by developernotes** [comment]
Hello @zhugscn 

I wanted to let you know that we have released a new version of SQLCipher for Android 3.5.7 which may address the issue you reported (though our fix was specifically around the native `CursorWindow`, but it was related to the same Android OS version). You can find out more information regarding the release [here](https://discuss.zetetic.net/t/sqlcipher-for-android-3-5-7-release/2086/1). Would you give that a try and let us know your results? Thanks!
