### ISSUE TITLE
After upgrade from 3.5.4 to 3.5.7 error net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master

### ISSUE THREAD

**Issue by vokrut** [sqlcipher/android-database-sqlcipher#352]
After upgrading library from 3.5.4 to 3.5.7 some users getting error:

Caused by net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
       at net.sqlcipher.database.SQLiteCompiledSql.native_compile(SQLiteCompiledSql.java)
       at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
       at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
       at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
       at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
       at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
       at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1867)
       at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1785)
       at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2486)
       at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2415)
       at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1149)
       at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1212)
       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:129)

I can't reproduce this problem on my devices. What's the problem can be? Library less then 3.5.4 we've never using

**Comment by developernotes** [comment]
Hi @vokrut 

Unfortunately, without sufficient information, it is difficult to say what the cause of the error is currently. A few follow-up questions to consider:

1. Since it appears only some users are affected, are you certain they are correctly entering their password? If so, how?
2. Did anything else change in your application when you upgraded SQLCipher for Android from 3.5.4 to 3.5.7? If so, what changed?
3. What Android OS version and devices are reporting the issues?
4. Are you able to test your application on the devices reporting the issue?
5. What is the application attempting to do just before the exception occurs?

**Comment by jiaruiz** [comment]
i also have this problem

**Comment by jiaruiz** [comment]
os version is 7.1.1

**Comment by vokrut** [comment]
We've found a problem. It was with InstanceID.getInstance(context).getId() what was using for database password. And all time it was constant, but after last update google play service library this parameter was changed, so there're no problem with sqlcipher.

**Comment by developernotes** [comment]
Hello @vokrut 

Thank you for your follow-up, we are happy to hear you were able to locate the issue you were facing. Take care!
