### ISSUE TITLE
java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by NanLen** [sqlcipher/android-database-sqlcipher#353]
I have got a crash log in our log server, the sqlcipher version is 3.5.4, the mobile phone is Android 7.0。
below is the crash log ,can I get some help.

java.lang.NullPointerException: Attempt to get length of null array(Java:maxMemory=268435456, totalMemory=73625656, freeMemory=5059448; Native:NativeHeapSize=36700160, NativeHeapAllocatedSize=27680992, NativeHeapFreeSize=9019168)
at java.lang.Class.getConstructor0(Class.java:2197)
at java.lang.Class.getConstructor(Class.java:1683)
at net.sqlcipher.database.SQLiteDatabase.lock(SQLiteDatabase.java)
at net.sqlcipher.database.SQLiteQuery.fillWindow(SQLiteQuery.java)
at net.sqlcipher.database.SQLiteCursor.fillWindow(SQLiteCursor.java)
at net.sqlcipher.database.SQLiteCursor.getCount(SQLiteCursor.java)
at net.sqlcipher.AbstractCursor.moveToPosition(AbstractCursor.java)
at net.sqlcipher.AbstractCursor.moveToFirst(AbstractCursor.java)
at android.database.CursorWrapper.moveToFirst(CursorWrapper.java:71)
at de.greenrobot.dao.AbstractDao.loadUnique(AbstractDao.java)
at de.greenrobot.dao.AbstractDao.loadUniqueAndCloseCursor(AbstractDao.java)
at de.greenrobot.dao.InternalQueryDaoAccess.loadUniqueAndCloseCursor(InternalQueryDaoAccess.java)
at de.greenrobot.dao.query.Query.unique(Query.java)
at de.greenrobot.dao.query.QueryBuilder.unique(QueryBuilder.java)

**Comment by developernotes** [comment]
Hi @NanLen 

Would you try upgrading to the latest release of SQLCipher for Android, currently at 3.5.7 and let us know your results? Thanks!

**Comment by NanLen** [comment]
I will try, Thanks!

**Comment by developernotes** [comment]
Hello @NanLen 

Any updates on utilizing the latest SQLCipher for Android 3.5.7 within your project?

**Comment by NanLen** [comment]
yeah ,I have updated it ,this crash have not appeared.

**Comment by developernotes** [comment]
Hi @NanLen 

Thanks for the update!
