### ISSUE TITLE
Cannot start a transaction within a transaction: BEGIN EXCLUSIVE

### ISSUE THREAD

**Issue by GensaGames** [sqlcipher/android-database-sqlcipher#354]
During single transaction and saving some fields (Performing SQLiteDatabase.endTransaction()) we facing with common SQLiteConstraintException, and It's Ok.  But starting every next Transaction fails with new one SQLiteException all the time, until device restart application, or open/close DB. Seems that after receiving Error, previous transaction cannot release Lock, and it produce such errors. Thanks. 

```
net.sqlcipher.database.SQLiteConstraintException: FOREIGN KEY constraint failed: COMMIT;
	at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
	at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2161)
	at net.sqlcipher.database.SQLiteDatabase.endTransaction(SQLiteDatabase.java:707)
        .............
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
```

```
net.sqlcipher.database.SQLiteException: cannot start a transaction within a transaction: BEGIN EXCLUSIVE;
	at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
	at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2161)
	at net.sqlcipher.database.SQLiteDatabase.beginTransactionWithListener(SQLiteDatabase.java:649)
	at net.sqlcipher.database.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:601)
        ................
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
```

### Expected Behavior
- Transaction RollBack and release all locks for the current Transaction. 

### Actual Behavior
- Previous failed Transaction still use lock, and all next operation fails to start. 

### Steps to Reproduce
 - Don't have steps. Random Devices. 

###  SQLCipher version :
- Using "net.zetetic:android-database-sqlcipher:3.5.2"

**Comment by developernotes** [comment]
Hi @GensaGames 

Would you try using the latest version of SQLCipher for Android, currently 3.5.7? Would you create a reproducible test case for further review using the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? We would be happy to investigate this further. Thanks!

**Comment by GensaGames** [comment]
I will update with results. @developernotes  Thanks.

**Comment by developernotes** [comment]
Hello @GensaGames 

Any update on utilizing the latest SQLCipher for Android 3.5.7 within your project?

**Comment by GensaGames** [comment]
It was reported from the Crashlytics logs and end Users. So far, we don't have this issue. I will update issue otherwise. Thanks.

**Comment by developernotes** [comment]
Thanks for the update @GensaGames!
