### ISSUE TITLE
not an error

### ISSUE THREAD

**Issue by zhangxi28** [sqlcipher/android-database-sqlcipher#367]
I  got error like below：

net.sqlcipher.database.SQLiteException: not an error
	at net.sqlcipher.database.SQLiteDatabase.dbopen(Native Method)
	at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:1951)
	at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:901)
	at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:944)
	at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:107)
	at com.ztgame.tw.persistent.AtDBHelper.openDatabase(AtDBHelper.java:67)

**Comment by developernotes** [comment]
Hi @zhangxi28 

Are you able to reproduce the exception you are receiving? Does it happen on a specific device and/or Android OS? We would be happy to investigate it further if you can reproduce the issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests). Please provide additional context into the issue you are experiencing as we are unable to assist you without additional specific information. Thanks!

**Comment by brodybits** [comment]
> We would be happy to investigate it further if you can reproduce the issue within the SQLCipher for Android test suite.

Hi I am very sorry to say that I find <https://github.com/sqlcipher/sqlcipher-android-tests> to be excessively confusing for the user community to demonstrate this kind of an issue. I would personally say that SQLCipher for Android should never throw an exception that says "not an error", and we should make it as easy as possible for the user community to submit reproducible test programs that we can then investigate, fix, and cover within the test suite.

@zhangxi28 if you can make a test project that is as simple as possible and completely self-contained (all dependencies automatically included), and then post it to GitHub with a permissive license such as MIT/BSD/Apache 2.0, I would be very happy to personally investigate the root cause and a possible solution. If you cannot reproduce the issue from scratch a possible technique could be to take your existing program and remove one thing at a time until you get it down to something simple enough for us to investigate.

**Comment by developernotes** [comment]
Hi @brodybits 

>Hi I am very sorry to say that I find https://github.com/sqlcipher/sqlcipher-android-tests to be excessively confusing for the user community to demonstrate this kind of an issue.

Could you provide some more specific feedback on what you find to be confusing about the SQLCipher for Android test suite? In practice, it should be one of the easiest ways for a developer to provide reproduction, since all they need to do is clone the project, copy a test, edit and run. That said, we'd of course accept any working reproduction to help troubleshoot - we wouldn't turn away a documented, reproducible bug, even if it wasn't in test suite form.

> you can make a test project that is as simple as possible and completely self-contained (all dependencies automatically included), and then post it to GitHub with a permissive license such as MIT/BSD/Apache 2.0

The SQLCipher for Android test suite is just that, an isolated application that attempts to be a canonical source of behaviors we wish to verify remain unchanged between releases of the library. I have found it to be quite beneficial in helping identify behavioral issues with the library, and being a tool for others to use when they report issues as it allows users to isolate their problem from their main application (something you are asking @zhangxi28 to do above).

The SQLCipher for Android test suite should become easier to use with our next release as the project has been restructured to utilize Gradle.

>I would personally say that SQLCipher for Android should never throw an exception that says "not an error"

SQLCipher for Android is reporting the value returned from [`sqlite3ErrStr`](https://www.sqlite.org/cgi/src/info/cb9af8293624da35), that is a value that comes directly from SQLite. With regard to error messages, we would all love to have a world where error messages are perfectly clear and contain no ambiguity. However, we are limited by the error's produced by the native library. You contributed a number of improvements to the error handling and reporting. Perhaps this user isn't running a recent version? Hopefully they will provide some additional information, at which point your offer to work directly with this user to investigate the root cause would be quite welcome.

We often receive straggling reports of errors users receive with little contextual information regarding the situation at hand. This post in an example of that. We use a Github Issue template to ask an initial set of questions such as:

1. The expected and actual behavior?
2. Which steps are required to reproduce the situation?
3. What SQLCipher and SQLCipher for Android version is being used?

@zhangxi28 did not provide answers to any of those questions. There is no code, no mention of the SQLCipher version, not even a rough outline of the scenario where the user sees this happening. Compare this to another bug report that we are currently working on, here:  https://github.com/sqlcipher/sqlcipher/issues/255 - I'm sure you'll agree that there is a considerable difference. Asking the user to replicate their error in isolation within the SQLCipher for Android test suite can help suss out the specific details.

We appreciate your willingness to assist other SQLCipher for Android users, and we welcome constructive criticism regarding SQLCipher. If you have anything additional to share, we would love to hear it.

**Comment by brodybits** [comment]
> Could you provide some more specific feedback on what you find to be confusing about the SQLCipher for Android test suite?

My apologies if this is excessively long-winded. If I would imagine the general mindset of a number of the library users with often very limited experience in all parts of Android development then I would imagine a very unpleasant mixture of confusion and frustration upon encountering this kind of an issue. I think we can agree that we need to manage the balance between our need for straightforward, reproducible bug reports and the process a library user would have to go through to get the test program to the required state.

In order to get a reproducible test program I would favor a template with as few classes as possible for the user to deal with. Ideally 1-2 classes that would wait for the user to press a button, open a test database, attempt some kind of an SQL operation, and alert the user with the results. If I would look through the test suite src tree with the extra helper/adapter classes and multiple content providers along with tests, runner, and result classes mixed together then I would consider this to be non-trivial for newbie Java developers to deal with.

In certain cases where the user cannot readily make a test program to reproduce the issue then the obviously correct process would be to make a copy of the application code and remove one thing at a time until the actual issue is sufficiently isolated. In some cases other refactoring steps may be obviously needed to remove sensitive business-specific information from the test program. While this process should be self-evident to more experienced developers I would imagine a number of novices would need some more explicit guidance.

To expand further on a self-evident point: by novices I mean affordable programmers (hackers) and smart business people. While I would imagine that SQLCipher library users should have a certain expected level of software expertise I am afraid that this will all too often not be the case in the future.

I would definitely agree with your other points in general, especially about sqlcipher/sqlcipher#255. Once someone raises an issue with a reproducible test program or otherwise enough detail for the SQLCipher experts to reproduce then I would definitely agree that someone should add a case to the test suite to verify the issue is resolved properly and the resolution continues to work correctly in the future.

An additional idea could be to update SQLCipher to include a version number or code within the error message that will show up whenever a user copy-pastes the exception message.

Moving forward I would be happy to propose a dead simple template that people can use to submit the needed test programs, probably sometime in January. In case further discussion is needed I would be happy to continue on the Zetetic Discuss forum, in GitHub, or even privately if needed. I would like to thank you guys again for your efforts to publish and maintain this wonderful software.

**Comment by sjlombardo** [comment]
Hello @brodybits - thanks for taking the time to respond here. We certainly would not object to having users submit issues using a simple application template. Please feel free to put together a sample project that you think would address this, and we'll take a look. In the mean time, we've updated the Android Test Suite README to include more specific, stepwise directions for how to write a new test to reproduce behavior. 

With regard to the idea of including a version number in the error strings, we can consider that idea for a future release. We'd need to evaluate whether that would be practical to include.  

One final comment, just to close the loop, is that even with a simplified template we can't completely eliminate the user responsibility for submitting actionable information. They need to take the time to understand what they are doing, and if they run into problems, submit enough information to help.

**Comment by developernotes** [comment]
Hi @zhangxi28,

I just wanted to follow-up regarding your initial report. Were you able to reproduce the exception you are receiving? Does it happen on a specific device and/or Android OS? We have since updated the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) which should make running and adding addition test scenarios easier.

**Comment by developernotes** [comment]
Hi @zhangxi28 

As we have not heard back from you, we will close this issue for the time being. If you are able to reliably reproduce the behavior, please feel free to open a new issue with additional reproduction steps. Thanks!
