### ISSUE TITLE
SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master with library 3.5.9

### ISSUE THREAD

**Issue by jaspreeterlang** [sqlcipher/android-database-sqlcipher#390]
```
E/Database: file is not a database: , while compiling: select count(*) from sqlite_master;
                                                    net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
                                                        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
                                                        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
                                                        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
                                                        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
                                                        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
                                                        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
                                                        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1867)
                                                        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1785)
                                                        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2486)
                                                        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2415)
                                                        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1149)
                                                        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1212)
                                                        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
                                                        at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:227)
                                                        at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:214)
                                                        at myapp.persistance.DatabaseBackend.getMyReadableDatabase(DatabaseBackend.java:570)
                                                        at myapp.ui.SplashActivity.finishSetup(SplashActivity.java:293)
```

### Expected Behavior
- Should be working on Android physical devices and emulators.

### Actual Behavior
- Code works on emulators but not able to work on physical devices.
- Crashes on application fresh install. So I am not able to proceed further with my application.

**Steps to Reproduce**
Code style:-
1. Put `SQLiteDatabase.loadLibs(this);` in `Application` class method:  `onCreate()`
2. Add code in SplashActivity (i.e. First activity who will start as launcher):
       ```DatabaseBackend databaseBackend = DatabaseBackend.getInstance(mContext);
        databaseBackend.getMyReadableDatabase();```
where `DatabaseBackend` is class who `extends SQLiteOpenHelper`.

and here is it's method who throws exception:
```
public SQLiteDatabase getMyReadableDatabase() {
        return getReadableDatabase("LockDBNow"); // Line who throws exception.
        }
```

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
Code from Gradle file:-
`implementation 'net.zetetic:android-database-sqlcipher:3.5.9@aar'`

SQLCipher for Android version:
I am trying to test on Samsung device Android OS Ver 7.0 (API 24).

---------

**Comment by developernotes** [comment]
Hi @jaspreeterlang 

Are you able to reproduce this behavior directly within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? Your scenario sounds quite similar to the [ReadableDatabaseTest](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/app/src/main/java/net/zetetic/tests/ReadableDatabaseTest.java). Would you share your results from the test suite? Thanks!

**Comment by gttiankai** [comment]
I have the same problem.

**Comment by jilegehuang** [comment]
I have the same problem,it will be OK when ues sqlite .
![_067](https://user-images.githubusercontent.com/32219063/43890630-d2fcbe1a-9bf9-11e8-8221-e11c3404d18b.png)

**Comment by developernotes** [comment]
Hi @gttiankai, @jilegehuang 

What were your results with [this](https://github.com/sqlcipher/android-database-sqlcipher/issues/390#issuecomment-400296273) inquiry?

**Comment by chenli3238** [comment]
only API >=24

**Comment by developernotes** [comment]
Hello @chenli3238 

Have you tried running something such as the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on any of your devices running an Android API greater than 24? What was your result?

**Comment by developernotes** [comment]
Hello,

This issue is being closed due to inactivity. If you have additional information to shared please feel free to open a new issue detailing the problem. Thanks
