### ISSUE TITLE
UnsatisfiedLinkError 

### ISSUE THREAD

**Issue by MaTriXy** [sqlcipher/android-database-sqlcipher#397]
**Error** 
`SQLiteDatabase$1 line 213 net.sqlcipher.database.SQLiteDatabase$1.loadLibraries`

This happens on GI-I9500_TMMARS running Android version 5.1 

**StackTrace :** 

`Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sample.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sample.test-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libsqlcipher.so"
       at java.lang.Runtime.loadLibrary(Runtime.java:377)
       at java.lang.System.loadLibrary(System.java:988)
       at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SourceFile:213)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:230)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:209)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:202)
       at com.commonsware.cwac.saferoom.Helper.(SourceFile:39)
       at com.commonsware.cwac.saferoom.SafeHelperFactory.create(SourceFile:122)
       at com.commonsware.cwac.saferoom.SafeHelperFactory.create(SourceFile:116)
       at com.sample.test.data.db.Database_Impl.access$302(SourceFile:205)
       at android.arch.persistence.room.RoomDatabase.createOpenHelper(SourceFile:110)
       at android.arch.persistence.room.RoomDatabase$Builder.build(SourceFile:631)
       at com.sample.test.data.db.Database$Companion.buildDatabase(SourceFile:44)
       at com.sample.test.data.db.Database$Companion.getInstance(SourceFile:36)
       at com.sample.test.app.onCreate(SourceFile:50)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4577)
       at android.app.ActivityThread.access$1500(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5278)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

sqlcipher for android version : 3.5.9
Using saferoom version 0.4.4

**Comment by developernotes** [comment]
Hi @MaTriXy,

It may be helpful to post some sample code that shows how you are initializing the libraries as that will be helpful in understanding what is occurring.

**Comment by developernotes** [comment]
Hi @MaTriXy 

Are you utilizing ProGuard by chance? If so, would you temporarily disable it and see if the behavior changes. @commonsguy, do you have any suggestions as to why cwac-saferoom would not be bundling the native libraries?

**Comment by commonsguy** [comment]
@MaTriXy Check your APK and see if the SQLCipher binaries are packaged inside of it. If yes, then I am not certain what is going on. If no, then we have some sort of dependency problem with SafeRoom, in which case it would be interesting to see a Gradle dependency report for the project.

**Comment by developernotes** [comment]
Hi @MaTriXy 

Just a follow-up to @commonsguy's suggestion, you can unpack your APK using [apktool](https://ibotpeaches.github.io/Apktool/).

**Comment by MaTriXy** [comment]
Hi, 
I've tested the apk and the SQLCipher binaries are in the apk. 
I've abi splits as well but in all apks you have the SQLCipher binaries.

**Comment by commonsguy** [comment]
@MaTriXy At this point, the best thing that I can recommend is to:

- Create a scrap project
- Add the SafeRoom dependency there
- Add some rudimentary Room code, enough to see whether it and SafeRoom works
- Try running the project

If this fails with the same problem, you now have a reproducible test case, and I would be happy to look at it.

If this succeeds, then slowly start modifying the Gradle configuration to look more like your real project (e.g., add in the APK splits). If at some point it breaks, that's now the reproducible test case.

**Comment by MaTriXy** [comment]
@commonsguy The issue here is Room + SafeRoom + SqlCipher works on all api versions but 
I've got this issue on that single device - Running on Nexus 5 for example with the same OS version works. 
As for recommended steps - i've done that to see if this is because of ABI splits but not reproducible,  for now at least.

**Comment by developernotes** [comment]
Hi @MaTriXy 

What does that device report from `Build.CPU_ABI`? Can you provide a screenshot of the unpacked APK with the folders expanded showing the included native libraries?

**Comment by MaTriXy** [comment]
Hi @developernotes , 

I've done a bit more digging to try and find the device and all the info i can.  

TMMARS appears to be software from Trend Micro.

Trend Micro Mobile App Reputation Service or TMMARS is a cloud-based service that automatically identifies mobile threats based on app behaviours.
It is extremely likely that the system is not behaving as the App expects it to, simply because it is a threat detection environment.
=======
So it might be their cloud service trying to check the app?

**Comment by developernotes** [comment]
Hello @MaTriXy 

That very well may be, [their](https://mars.trendmicro.com/) service doesn't provide much additional information. At this point I will close this issue, please feel free to open a new issue if you have more information that might suggest a problem with SQLCipher for Android.
