### ISSUE TITLE
can not open database file when sqlcipher 3.5.9 update to 4.0.0 net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;

### ISSUE THREAD

**Issue by HaidyCao** [sqlcipher/android-database-sqlcipher#406]
### Expected Behavior
 Not throw that Exception and open database succeed
### Actual Behavior
 throw a exception: 

net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1954)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1840)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2571)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2502)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1204)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1258)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1253)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1238)
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
4.0.0
SQLCipher for Android version:
4.0.0
*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by theBlbDan** [comment]
Your "Steps to Reproduce" do not explain how to reproduce the error thrown.

Can you explain where your database file is located and how you are providing it to the openOrCreateDatabase() method?

Providing a stack trace form the net.sqlcipher.database.SQLiteDatabase class and basically saying "It doesn't work" isn't sufficient for anybody to help you.  If you can provide a stack trace showing where in your code it crashes and then a copy of that section of code, it would greatly help.

**Comment by HaidyCao** [comment]
database file is on /data/data/package.name/files/*.db

I just call 
mDb = SQLiteDatabase.openOrCreateDatabase(new File(context.getFilesDir(), DB_NAME),
                    databaseCipher, null, new MySQLiteDatabaseHook());

public class MySQLiteDatabaseHook implements SQLiteDatabaseHook {

    @Override
    public void postKey(SQLiteDatabase database) {
        database.rawExecSQL("PRAGMA kdf_iter = 4000");
    }

    @Override
    public void preKey(SQLiteDatabase database) {

    }

}

**Comment by HaidyCao** [comment]
I found resolvent in [](https://www.zetetic.net/blog/)

Compatibility
Many of these changes provide a much higher level of security than previous versions of SQLCipher. However, the new page size of 4096, 256,000 KDF iterations, use of PBKDF2-HMAC-SHA512 and HMAC-SHA512 all modify important database settings. Thus, SQLCipher 4 will not open older databases by default. As always, we have updated our migration feature to streamline the upgrade process. To enable backwards-compatibility, it is possible to adjust settings at runtime or migrate older databases:

To migrate and upgrade an existing database in place (preserving data and schema), use the new default settings, use PRAGMA cipher_migrate.
To open an older database used pragmas to adjust settings back to their previous values. For example, to open a SQLCipher 3 database using SQLCipher 4, you could use the following statements after opening and keying the database: PRAGMA cipher_page_size = 1024; PRAGMA kdf_iter = 64000; PRAGMA cipher_hmac_algorithm = HMAC_SHA1; PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA1;
To attach and export data to a new database, use the sqlcipher_export() convenience function. This would let you control migration using very specific or custom settings.

I prepare to test it.
