### ISSUE TITLE
can't open encrypted database using cwac-saferoom

### ISSUE THREAD

**Issue by hannesa2** [sqlcipher/android-database-sqlcipher#408]
### Expected Behavior
Usage of encrypted db without any crash

### Actual Behavior
```
    java.lang.RuntimeException: Unable to create application net.demo.partnerapp.CouchApp: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1954)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1840)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2571)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2502)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1204)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1267)
        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
        at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWritableSupportDatabase(Helper.java:142)
        at com.commonsware.cwac.saferoom.Helper.getWritableDatabase(Helper.java:77)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:238)
```
# A update behavior
### Steps to Reproduce
I run into following after error update from `com.commonsware.cwac:saferoom.x:0.5.1` to `com.commonsware.cwac:saferoom.x:1.0.0-alpha1`
It means update from
`"PRAGMA cipher_page_size = 1024; PRAGMA kdf_iter = 64000; PRAGMA cipher_hmac_algorithm = HMAC_SHA1; PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA1;";` 
to
`"PRAGMA cipher_compatibility = 3;";`

SQLCipher for Android version:
update from
`android-database-sqlcipher:3.5.9`
to
`android-database-sqlcipher:4.0.1`

# B no update
### Steps to Reproduce
in crashlytics we see some crashes without update, they can't open encrypted database
using `com.commonsware.cwac:saferoom.x:0.5.1`

`"PRAGMA cipher_page_size = 1024; PRAGMA kdf_iter = 64000; PRAGMA cipher_hmac_algorithm = HMAC_SHA1; PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA1;";` 

SQLCipher for Android version:
`android-database-sqlcipher:3.5.9`

Here is the same issue https://github.com/commonsguy/cwac-saferoom/issues/41

**Any ideas ?**

**Comment by sjlombardo** [comment]
@hannesa2  - have you followed the advise in the [SafeRoom documentation](https://github.com/commonsguy/cwac-saferoom/blob/master/README-1.0.0.md#usage) (also referenced in the other issue) regarding backwards compatibility via either `SafeHelperFactory.POST_KEY_SQL_V3` or `SafeHelperFactory.POST_KEY_SQL_MIGRATE`?
