### ISSUE TITLE
Error file is not a database while open SQLite database from assets

### ISSUE THREAD

**Issue by kaiv2000** [sqlcipher/android-database-sqlcipher#413]
While opening database created at PC using SQLite from asset folder from version 4.0.0 appear error while opening database using next code:
Database was created emty and then replaced by filled database from asset folder.

SQLiteDatabase   database = SQLiteDatabase.openDatabase(databaseFile.getPath(), password, null, SQLiteDatabase.OPEN_READONLY);

Error:

E/Database: file is not a database: , while compiling: select count(*) from sqlite_master;
            net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
                at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
                at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
                at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
                at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
                at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
                at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
                at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1954)
                at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1840)
                at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2571)
                at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2502)
                at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1204)
                at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1171)
                at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1120)
                at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1074)
                at com..readChannelListFromDb(DatabaseOperations.java:43)
                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                at java.lang.Thread.run(Thread.java:761)

**Comment by developernotes** [comment]
Hi @kaiv2000 

What version of SQLCipher was used to create the database on your PC?

**Comment by kaiv2000** [comment]
DB was created via SQLite software version 3.10.1 with SQLChiper 3.15.2

**Comment by developernotes** [comment]
Hello @kaiv2000 

The the release of [SQLCipher 4](https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/), changes including the new page size of 4096, 256,000 KDF iterations, use of PBKDF2-HMAC-SHA512 and HMAC-SHA512 all modify important database settings. Thus, SQLCipher 4 will not open older databases by default. Please review the [upgrading to SQLCipher 4 guidance](https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283).
