### ISSUE TITLE
Android  file is not a database: 

### ISSUE THREAD

**Issue by RajeshDhalange** [sqlcipher/android-database-sqlcipher#418]
I am using 'net.zetetic:android-database-sqlcipher:4.0.1@aar'
I have pre-populated SQLite database with FTS-4
Steps I Followed
1. Open database in DbBrowser and set encryption key 
2. Copy db file to android and trying to access it but giving the following error
* without encryption it's working fine

`E/Database: file is not a database: , while compiling: select count(*) from sqlite_master;
    net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1954)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1840)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2571)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2502)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1204)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1171)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1120)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1074)
 `

**Comment by RajeshDhalange** [comment]
After downgrading library to 'net.zetetic:android-database-sqlcipher**:3.5.9'** it working

**Comment by theBlbDan** [comment]
@RajeshDhalange 

FYI:  https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283
