### ISSUE TITLE
net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master

### ISSUE THREAD

**Issue by Xdomino** [sqlcipher/android-database-sqlcipher#479]
Hi, I'm trying to use sqlcipher in an exist android project. But i got error. I also tried to looking solution in issues, but in vain. It will be so so so thankful if get help.

The original code was native api(from package `android.database.sqlite`). And i followed document converted code to package(`net.sqlcipher.database`). But when i run the code. It got blow error.

I'm not using `SQLiteDatabase.openOrCreateDatabase()`, instead of `SQLiteOpenHelper.getWritableDatabase()`. All code is in native way, except from `net.sqlcipher.database`.

`net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2012)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1898)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2647)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2577)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1243)
        at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:263)
        at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:228)
        at net.sqlcipher.database.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:224)`

**Comment by developernotes** [comment]
Hi @Xdomino 

We reserve GitHub Issues for reporting defects within the software library itself. An integration question is best posted within the SQLCipher community [discuss site](https://discuss.zetetic.net/c/sqlcipher). It would be helpful when reposting to include a bit more information regarding whether your database already exists or not, whether it is a plaintext SQLite database, or a SQLCipher database, and the code you are executing. Thanks!
