### ISSUE TITLE
sqlcipher4.1.0 donot work on android 6.0 

### ISSUE THREAD

**Issue by qiantanlong** [sqlcipher/android-database-sqlcipher#485]
,error:java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy4" referenced by "/data/app/com.hisign.sqlciphertools-2/lib/arm/libsqlcipher.so"
 at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:223)
        at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:240)
        at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:219)
        at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:212)
        at com.hisign.sqlciphertools.MainActivity.onCreate(MainActivity.java:39)
        at android.app.Activity.performCreate(Activity.java:6266)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)

**Comment by developernotes** [comment]
Hi @qiantanlong 

Have you tried the latest SQLCipher for Android 4.2.0 release? If not, would you try that and report back?
