### ISSUE TITLE
application getting crash  after replacing database plain text key with encrypted key

### ISSUE THREAD

**Issue by manishakamble** [sqlcipher/android-database-sqlcipher#486]
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by manishakamble** [comment]
Caused by: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(Unknown Source:15)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(Unknown Source:43)
        at net.sqlcipher.database.SQLiteProgram.<init>(Unknown Source:116)
        at net.sqlcipher.database.SQLiteQuery.<init>(Unknown Source:0)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(Unknown Source:7)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(Unknown Source:35)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(Unknown Source:1)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(Unknown Source:30)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(Unknown Source:14)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(Unknown Source:14)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(Unknown Source:7)
        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(Unknown Source:91)
        at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWritableSupportDatabase(Unknown Source:4)
        at com.commonsware.cwac.saferoom.Helper.getWritableDatabase(Unknown Source:6)
        at androidx.room.RoomDatabase.inTransaction(Unknown Source:2)
        at androidx.room.RoomDatabase.assertNotSuspendingTransaction(Unknown Source:0)
        at com.kioskengineproject.dao.DaoAccess_Impl.insertBins(Unknown Source:2)
        at com.kioskengineproject.repository.KioskEngineRepository$1.doInBackground(Unknown Source:12)
        at com.kioskengineproject.repository.KioskEngineRepository$1.doInBackground(Unknown Source:2)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)

**Comment by developernotes** [comment]
Hi @manishakamble 

Can you share a bit more about what you're attempting to do? Are you utilizing the `PRAGMA rekey` functionality? Are you able to reproduce the issue?

**Comment by manishakamble** [comment]
Hi 
the issue is resolved . that PRAGMA rekey documentation helps me .thank you so much .

**Comment by developernotes** [comment]
Hi @manishakamble 

That is great to hear, thank you for your follow-up!
