### ISSUE TITLE
net.sqlcipher.database.SQLiteException

### ISSUE THREAD

**Issue by lks6123** [sqlcipher/android-database-sqlcipher#487]
### Steps to Reproduce

SQLCipher version:4.2.0

SQLCipher for Android version:4.2.0

```
2019-12-18 16:15:13.148 2624-2718/com.tct.globalnet E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.tct.globalnet, PID: 2624
    net.sqlcipher.database.SQLiteException: no such collation sequence: LOCALIZED: , while compiling: SELECT * FROM country WHERE langType = ? AND telprex is not null AND iso2!='ALL' ORDER BY countryName COLLATE LOCALIZED ASC
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:91)
        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2016)
      
```

**Comment by sjlombardo** [comment]
Built in custom collations were removed from SQLCipher in version 3.5.0 (several years ago). See here for more details and options:

https://discuss.zetetic.net/t/workaround-for-using-androids-localized-collator-after-3-5-0-update/1515

**Comment by lks6123** [comment]
Thanks
