### ISSUE TITLE
SQLiteCompiledSql: Releasing statement in a finalizer. Please ensure that you explicitly call close()

### ISSUE THREAD

**Issue by slavonnet** [sqlcipher/android-database-sqlcipher#498]
```
// kodein
        bind<ExecutorService>() with eagerSingleton {
            Executors.newFixedThreadPool(24)
        }

        // Database
        bind<AppDatabase>() with eagerSingleton {
            val factory = SupportFactory("Password".toByteArray(), null, true)

            Room.databaseBuilder(
                    this@MyApplication,
                    AppDatabase::class.java,
                    "doc103.db"
                )
                .fallbackToDestructiveMigration()
                .openHelperFactory(factory)
                .setQueryExecutor(Dispatchers.IO.asExecutor())
                .setTransactionExecutor(Dispatchers.IO.asExecutor())
                .build()
        }

        bind<DictionaryDao>() with singleton { instance<AppDatabase>().directoryDao() }


// in dao:

    @Transaction
    @Query("UPDATE cards set locked = 1 where locked = 0 and id in (:ids) ")
    fun lockByIds(ids: List<String>)

    @Transaction
    @Query("UPDATE cards set locked = 0 where locked = 1 and id in (:ids) ")
    fun unLockByIds(ids: List<String>)

```
android-database-sqlcipher:4.3.0

many time warning exception. Only if usage sqlchiper:

```
W/SQLiteCompiledSql: Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: UPDATE cards set locked = 0 where locked = 1 and id in (?,?,?,?,?,?,?,?,?) 
    net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:111)
        at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:41)
        at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1706)
        at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:79)
        at androidx.room.RoomDatabase.compileStatement(RoomDatabase.java:341)
        at ru.sbssoft.kis.doc103.db.CardDao_Impl.unLockByIds(CardDao_Impl.java:19173)
        at ru.sbssoft.kis.doc103.workers.HeartbeatWorker.doWork(HeartbeatWorker.kt:196)
        at ru.sbssoft.kis.doc103.workers.HeartbeatWorker$doWork$1.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
I/chatty: uid=10150(ru.sbssoft.kis.doc103) FinalizerDaemon identical 1 line
W/SQLiteCompiledSql: Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: UPDATE cards set locked = 0 where locked = 1 and id in (?,?,?,?,?,?,?,?,?) 
    net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:111)
        at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:41)
        at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1706)
        at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:79)
        at androidx.room.RoomDatabase.compileStatement(RoomDatabase.java:341)
        at ru.sbssoft.kis.doc103.db.CardDao_Impl.unLockByIds(CardDao_Impl.java:19173)
        at ru.sbssoft.kis.doc103.workers.HeartbeatWorker.doWork(HeartbeatWorker.kt:196)
        at ru.sbssoft.kis.doc103.workers.HeartbeatWorker$doWork$1.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by developernotes** [comment]
Hi @slavonnet 

Are you able to reproduce this behavior with a Room test within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? If so, we'd be happy to look into this further. Thanks!

**Comment by slavonnet** [comment]
i can't chreate test.Problem is here.

**Comment by developernotes** [comment]
Hello @slavonnet 

What is the issue in creating a test case to reproduce the issue you are expereiencing?

**Comment by TadejZupancic** [comment]
Hi, I also see this warning in my app. I've managed to create a short code to reproduce it.  

In my app I insert/delete a lot of different data to different tables during sync with server, but here it looks like only the functions need to be called, even if they don't change the database and it also produces a warning. The code is [here](https://dileque.si/files/deletetest.zip)

If  you comment out the use of openHelperFactory, the problem does not appear.

**Comment by developernotes** [comment]
Hi @TadejZupancic 

Would it be possible for you to post your code sample on GitHub for further review? Thanks!

**Comment by TadejZupancic** [comment]
Sure, here's the link: [https://github.com/TadejZupancic/sqlcipher-deletetest](https://github.com/TadejZupancic/sqlcipher-deletetest)

**Comment by iskugor** [comment]
I'm also seeing this on some devices. Not sure how to reproduce it, but I think it's related to Android Room usage.

> Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here

**Comment by developernotes** [comment]
Hi @slavonnet, @TadejZupancic 

Thank you for the reproduction case. We have removed the warning as the underlying resource is cleaned up afterwards. This will be available in the next public SQLCipher for Android release. Thanks!
