### ISSUE TITLE
TimeoutException for SQLiteDatabase.java line 570

### ISSUE THREAD

**Issue by alla2040** [sqlcipher/android-database-sqlcipher#509]
I am using Room with sqlcipher lib. On some devices there is a crash (details below).

### Expected Behavior
no crash
### Actual Behavior
crash in SQLiteDatabase.java line 570:
Fatal Exception: java.util.concurrent.TimeoutException: net.sqlcipher.database.SQLiteCompiledSql.finalize() timed out after 10 seconds
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`): 

SQLCipher for Android version: 4.3.0

Fatal Exception: java.util.concurrent.TimeoutException: net.sqlcipher.database.SQLiteCompiledSql.finalize() timed out after 10 seconds
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2163)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:868)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:900)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1223)
       at java.util.concurrent.locks.ReentrantLock$FairSync.lock(ReentrantLock.java:225)
       at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:286)
       at net.sqlcipher.database.SQLiteDatabase.lock(SQLiteDatabase.java:570)
       at net.sqlcipher.database.SQLiteCompiledSql.releaseSqlStatement(SQLiteCompiledSql.java:106)
       at net.sqlcipher.database.SQLiteCompiledSql.finalize(SQLiteCompiledSql.java:152)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
       at java.lang.Daemons$Daemon.run(Daemons.java:103)
       at java.lang.Thread.run(Thread.java:784)

**Comment by developernotes** [comment]
Hi @alla2040 

Are you able to create a reproducible test case within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? If so, we would be happy to investigate this further. Thanks!

**Comment by alla2040** [comment]
I do not know, how to reproduce it. I have crashes from users in Crashlytics.

**Comment by developernotes** [comment]
Hello @alla2040 

Unfortunately, a stack trace alone is not enough information to isolate an issue within SQLCipher for Android. We would ask that you review your application code to see where the call site might occur for the error when utilizing the library, evaluate the SQL command(s) being executed, and try to provide any additional information where you can. Without additional information, we are unable to provide direction for next steps.

**Comment by developernotes** [comment]
Hello @alla2040 

Do you have any feedback to offer with regard to our suggestions [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/509#issuecomment-620606282)?

**Comment by alla2040** [comment]
Hi! You proposed  to check my code, how I open/close the connection. If you mean the database, then I don't use Cursor there , since I use Room, so I don't open/close Cursor. And it is not obligatory to force to close the database, but keep the connection open during the life of the app (according to google developers' Room samples). I don't close the database in Room and don't open it, I build it, it opens under the hood. In SQLiteDataBase I open/close it, but not in Room.

**Comment by developernotes** [comment]
Hi @alla2040 

Do you know what queries are being run when the crash occurs?

**Comment by alla2040** [comment]
Unfortunately, no. I only see crashes in Crashlytics
