### ISSUE TITLE
Caused by: net.sqlcipher.database.SQLiteDiskIOException: disk I/O error: BEGIN EXCLUSIVE;

### ISSUE THREAD

**Issue by Mangosir** [sqlcipher/android-database-sqlcipher#511]
The crash stack trace:
java.lang.RuntimeException: Unable to create application com.xhz.bo.application.PrintApp: net.sqlcipher.database.SQLiteDiskIOException: disk I/O error: BEGIN EXCLUSIVE;
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6545)
    at android.app.ActivityThread.access$1400(ActivityThread.java:220)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:7520)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: net.sqlcipher.database.SQLiteDiskIOException: disk I/O error: BEGIN EXCLUSIVE;
    at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
    at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:4)
    at net.sqlcipher.database.SQLiteDatabase.beginTransactionWithListener(SQLiteDatabase.java:8)
    at net.sqlcipher.database.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:1)
    at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:16)
    at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:1)

I get a crash when the application is created, the database located SD card
SQLCipher for Android version:3.5.7

**Comment by developernotes** [comment]
Hello @Mangosir 

From the exception you received, it appears SQLCipher was unable to access the path to the database. Please make sure you have read/write access to the file path.

**Comment by Mangosir** [comment]
> Hello @Mangosir
> 
> From the exception you received, it appears SQLCipher was unable to access the path to the database. Please make sure you have read/write access to the file path.

thanks @developernotes Nick Parker
the database path is ../Android/data/com.xhz.bo/cache/,
No permission required to access these files, 
so...

**Comment by developernotes** [comment]
Hi @Mangosir 

Are you able to create a reproducible test case within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?
