### ISSUE TITLE
UnsatisfiedLinkError: dalvik.system.PathClassLoader......couldn't find "libsqlcipher.so"

### ISSUE THREAD

**Issue by Yang-Shuang** [sqlcipher/android-database-sqlcipher#522]
**Error :** 
**Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/com.huimai365-BFceNclOc4idFxd_7uUZhQ==/base.apk", dex file "/data/app/com.huimai365-BFceNclOc4idFxd_7uUZhQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.huimai365-BFceNclOc4idFxd_7uUZhQ==/lib/arm, /data/app/com.huimai365-BFceNclOc4idFxd_7uUZhQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]] couldn't find "libsqlcipher.so"**

**dependencies:**
   **api 'net.zetetic:android-database-sqlcipher:3.5.6'**

**Crash Mobile: 华为 PRA-AL00   Android 8.0.0  arm64-v8a**

I had use apktool decode my apk, the **lib** has two folder **armeabi** and **armeabi-v7a**, and they also include **libsqlcipher.so**.    But on the 华为 PRA-AL00(Android 8.0.0  arm64-v8a),it crashed.   what's wrong?  
Error Details:

Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/com.huimai365-BFceNclOc4idFxd_7uUZhQ==/base.apk", dex file "/data/app/com.huimai365-BFceNclOc4idFxd_7uUZhQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.huimai365-BFceNclOc4idFxd_7uUZhQ==/lib/arm, /data/app/com.huimai365-BFceNclOc4idFxd_7uUZhQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]] couldn't find "libsqlcipher.so"
at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
at java.lang.System.loadLibrary(System.java:1660)
at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:213)
at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:230)
at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:209)
at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:202)

**Comment by developernotes** [comment]
Hi @Yang-Shuang 

`arm64-v8a` is included in the 3.5.6 version of SQLCipher for Android. Are you applying an `abiFilters` element within your build to limit the included architectures for your application? Please note the latest version of SQLCipher for Android os 4.4.0.

**Comment by Yang-Shuang** [comment]
Yes，I had apply an **abiFilters**   like this :
        **ndk {
                abiFilters 'armeabi','armeabi-v7a'
        }**
but the **arm64-v8a** device could have been backward compatible with **armeabi-v7a**, and my apk include the **.so** in the **armeabi-v7a** folder,  so  I can't understand why the device crashed, I tried on others **arm64-v8a** device, and these device didn't occur this problem。I hope you give some ideas to me, thanks!!!

**Comment by developernotes** [comment]
Hi @Yang-Shuang 

What happens when you only include `armeabi-v7a` in your `abiFilters`?

**Comment by Yang-Shuang** [comment]
I don't know, the broken device is belong to online user，I can‘t find the same device to test this problem, and my app have to use **armeabi** and **armeabi-v7a** together。
I think may be the device has something wrong.   😂 so I recommend users to reinstall the app， and have not received any feedback yet.

**Comment by wolfrex-666** [comment]
你这个问题解决了不？
