### ISSUE TITLE
App is crashing on few devices

### ISSUE THREAD

**Issue by arifur-chefling** [sqlcipher/android-database-sqlcipher#530]
Here is the stacktraces:

1.
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.chefling.chefling-1/base.apk"],nativeLibraryDirectories=[/data/app/com.chefling.chefling-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libsqlcipher.so"
       at java.lang.Runtime.loadLibrary(Runtime.java:367)
       at java.lang.System.loadLibrary(System.java:1076)
       at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:227)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:244)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:223)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:216)
       at net.sqlcipher.database.SupportHelper.<init>(SupportHelper.java:31)
       at net.sqlcipher.database.SupportFactory.create(SupportFactory.java:43)
       at com.chefling.chefling.database.CheflingDbHelper_Impl.createOpenHelper(CheflingDbHelper_Impl.java:213)
       at androidx.room.RoomDatabase.init(RoomDatabase.java:114)
       at androidx.room.RoomDatabase$Builder.build(RoomDatabase.java:668)
       at com.chefling.chefling.di.modules.ApplicationModule.provideCheflingDbHelper(ApplicationModule.java:334)
       at com.chefling.chefling.di.modules.ApplicationModule_ProvideCheflingDbHelperFactory.proxyProvideCheflingDbHelper(ApplicationModule_ProvideCheflingDbHelperFactory.java:70)
       at com.chefling.chefling.di.modules.ApplicationModule_ProvideCheflingDbHelperFactory.provideInstance(ApplicationModule_ProvideCheflingDbHelperFactory.java:48)
       at com.chefling.chefling.di.modules.ApplicationModule_ProvideCheflingDbHelperFactory.get(ApplicationModule_ProvideCheflingDbHelperFactory.java:39)
       at com.chefling.chefling.di.modules.ApplicationModule_ProvideCheflingDbHelperFactory.get(ApplicationModule_ProvideCheflingDbHelperFactory.java:12)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.chefling.chefling.di.modules.RepositoryModule_ProvidesNewCookbookLocalDataSource$app_prodReleaseFactory.provideInstance(RepositoryModule_ProvidesNewCookbookLocalDataSource.java:34)
       at com.chefling.chefling.di.modules.RepositoryModule_ProvidesNewCookbookLocalDataSource$app_prodReleaseFactory.get(RepositoryModule_ProvidesNewCookbookLocalDataSource.java:28)
       at com.chefling.chefling.di.modules.RepositoryModule_ProvidesNewCookbookLocalDataSource$app_prodReleaseFactory.get(RepositoryModule_ProvidesNewCookbookLocalDataSource.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.chefling.chefling.di.modules.RepositoryModule_ProvideNewCookbookRepositoryFactory.provideInstance(RepositoryModule_ProvideNewCookbookRepositoryFactory.java:167)
       at com.chefling.chefling.di.modules.RepositoryModule_ProvideNewCookbookRepositoryFactory.get(RepositoryModule_ProvideNewCookbookRepositoryFactory.java:120)
       at com.chefling.chefling.di.modules.RepositoryModule_ProvideNewCookbookRepositoryFactory.get(RepositoryModule_ProvideNewCookbookRepositoryFactory.java:28)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.chefling.chefling.di.modules.InteractorModule_ProvideAllReadyToCookRecipesInteractorFactory.provideInstance(InteractorModule_ProvideAllReadyToCookRecipesInteractorFactory.java:42)
       at com.chefling.chefling.di.modules.InteractorModule_ProvideAllReadyToCookRecipesInteractorFactory.get(InteractorModule_ProvideAllReadyToCookRecipesInteractorFactory.java:34)
       at com.chefling.chefling.di.modules.InteractorModule_ProvideAllReadyToCookRecipesInteractorFactory.get(InteractorModule_ProvideAllReadyToCookRecipesInteractorFactory.java:11)
       at com.chefling.chefling.recipe.viewmodel.RecipeViewModelImp_Factory.provideInstance(RecipeViewModelImp_Factory.java:293)
       at com.chefling.chefling.recipe.viewmodel.RecipeViewModelImp_Factory.get(RecipeViewModelImp_Factory.java:192)
       at com.chefling.chefling.recipe.viewmodel.RecipeViewModelImp_Factory.get(RecipeViewModelImp_Factory.java:42)
       at com.chefling.chefling.CheflingViewModelFactory.create(CheflingViewModelFactory.java:19)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
       at com.chefling.chefling.recipeimport.view.view.RecipeSearchActivity$recipeViewModel$2.invoke(RecipeSearchActivity.java:110)
       at com.chefling.chefling.recipeimport.view.view.RecipeSearchActivity$recipeViewModel$2.invoke(RecipeSearchActivity.java:63)
       at kotlin.SynchronizedLazyImpl.getValue(SynchronizedLazyImpl.java:74)
       at com.chefling.chefling.recipeimport.view.view.RecipeSearchActivity.getRecipeViewModel(RecipeSearchActivity.java)
       at com.chefling.chefling.recipeimport.view.view.RecipeSearchActivity.initObservers(RecipeSearchActivity.java:316)
       at com.chefling.chefling.recipeimport.view.view.RecipeSearchActivity.onCreate(RecipeSearchActivity.java:150)
       at android.app.Activity.performCreate(Activity.java:6280)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1116)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

2.
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.chefling.chefling-mLRAs06Ed5ADkCyiTbUKaQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.chefling.chefling-mLRAs06Ed5ADkCyiTbUKaQ==/lib/arm64, /system/lib64]]] couldn't find "libsqlcipher.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
       at java.lang.System.loadLibrary(System.java:1669)
       at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:227)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:244)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:223)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:216)
       at net.sqlcipher.database.SupportHelper.<init>(SupportHelper.java:31)
       at net.sqlcipher.database.SupportFactory.create(SupportFactory.java:43)
       at com.chefling.chefling.database.CheflingDbHelper_Impl.createOpenHelper(CheflingDbHelper_Impl.java:213)
       at androidx.room.RoomDatabase.init(RoomDatabase.java:114)
       at androidx.room.RoomDatabase$Builder.build(RoomDatabase.java:668)
       at com.chefling.chefling.di.modules.ApplicationModule.provideCheflingDbHelper(ApplicationModule.java:334)
       at com.chefling.chefling.di.modules.ApplicationModule_ProvideCheflingDbHelperFactory.proxyProvideCheflingDbHelper(ApplicationModule_ProvideCheflingDbHelperFactory.java:70)
       at com.chefling.chefling.di.modules.ApplicationModule_ProvideCheflingDbHelperFactory.provideInstance(ApplicationModule_ProvideCheflingDbHelperFactory.java:48)
       at com.chefling.chefling.di.modules.ApplicationModule_ProvideCheflingDbHelperFactory.get(ApplicationModule_ProvideCheflingDbHelperFactory.java:39)
       at com.chefling.chefling.di.modules.ApplicationModule_ProvideCheflingDbHelperFactory.get(ApplicationModule_ProvideCheflingDbHelperFactory.java:12)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.chefling.chefling.di.modules.RepositoryModule_ProvidesNewCookbookLocalDataSource$app_prodReleaseFactory.provideInstance(RepositoryModule_ProvidesNewCookbookLocalDataSource.java:34)
       at com.chefling.chefling.di.modules.RepositoryModule_ProvidesNewCookbookLocalDataSource$app_prodReleaseFactory.get(RepositoryModule_ProvidesNewCookbookLocalDataSource.java:28)
       at com.chefling.chefling.di.modules.RepositoryModule_ProvidesNewCookbookLocalDataSource$app_prodReleaseFactory.get(RepositoryModule_ProvidesNewCookbookLocalDataSource.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.chefling.chefling.di.modules.RepositoryModule_ProvideNewCookbookRepositoryFactory.provideInstance(RepositoryModule_ProvideNewCookbookRepositoryFactory.java:167)
       at com.chefling.chefling.di.modules.RepositoryModule_ProvideNewCookbookRepositoryFactory.get(RepositoryModule_ProvideNewCookbookRepositoryFactory.java:120)
       at com.chefling.chefling.di.modules.RepositoryModule_ProvideNewCookbookRepositoryFactory.get(RepositoryModule_ProvideNewCookbookRepositoryFactory.java:28)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.chefling.chefling.profile.interactor.UpdatePushTokenInteractor_Factory.provideInstance(UpdatePushTokenInteractor_Factory.java:31)
       at com.chefling.chefling.profile.interactor.UpdatePushTokenInteractor_Factory.get(UpdatePushTokenInteractor_Factory.java:26)
       at com.chefling.chefling.profile.interactor.UpdatePushTokenInteractor_Factory.get(UpdatePushTokenInteractor_Factory.java:9)
       at com.chefling.chefling.authentication.viewmodel.AuthenticationViewmodelImp_Factory.provideInstance(AuthenticationViewmodelImp_Factory.java:216)
       at com.chefling.chefling.authentication.viewmodel.AuthenticationViewmodelImp_Factory.get(AuthenticationViewmodelImp_Factory.java:150)
       at com.chefling.chefling.authentication.viewmodel.AuthenticationViewmodelImp_Factory.get(AuthenticationViewmodelImp_Factory.java:35)
       at com.chefling.chefling.CheflingViewModelFactory.create(CheflingViewModelFactory.java:19)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
       at com.chefling.chefling.authentication.view.AuthenticationActivity$authenticationViewModel$2.invoke(AuthenticationActivity.java:38)
       at com.chefling.chefling.authentication.view.AuthenticationActivity$authenticationViewModel$2.invoke(AuthenticationActivity.java:31)
       at kotlin.SynchronizedLazyImpl.getValue(SynchronizedLazyImpl.java:74)
       at com.chefling.chefling.authentication.view.AuthenticationActivity.getAuthenticationViewModel(AuthenticationActivity.java:2)
       at com.chefling.chefling.authentication.view.AuthenticationActivity.initObservers(AuthenticationActivity.java:55)
       at com.chefling.chefling.authentication.view.AuthenticationActivity.onCreate(AuthenticationActivity.java:45)
       at android.app.Activity.performCreate(Activity.java:7136)
       at android.app.Activity.performCreate(Activity.java:7127)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by developernotes** [comment]
Hello @arifur-chefling,

Can you tell us a bit more about the issue you're experiencing? The following questions would be helpful in helping diagnose the situation:

- What device(s) do you experience this issue on? 
- What version of the Android OS are they running?
- Does your application include an `abiFilters` section within Gradle?
- What version of SQLCipher for Android are you using?
- Are you able to reproduce this error consistently?
- What are your results from running the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on any devices reporting the error?

**Comment by arifur-chefling** [comment]
@developernotes 
We are unable to reproduce the crash but it was reported in our Firebase Crashlytics on two devices Pixel 3 XL(Android-9) and Nexus 4(Android 6.0.1). We don't have any abiFilters. SQLCipher version is 4.4.1 community.

**Comment by developernotes** [comment]
Hello @arifur-chefling 

We have verified the SQLCipher for Android test suite run successfully on a Pixel 3 device. Would you please try running [apktool](https://ibotpeaches.github.io/Apktool/) against your APK file submitted to the store and verify whether you are bundling `libsqlcipher.so` in the `x86` folder?

**Comment by nic-bell** [comment]
We've noticed something similar lots of `java.lang.UnsatisfiedLinkError` crashes in Crashlytics. 
It doesn't happen all the time though so it's hard to reproduce. There is a pattern in Crashlytics, it's usually Samsung devices running Android 8 and the crash usually appears while the app is in a background state.

**Comment by developernotes** [comment]
Hi @nic-bell 

Can you post the specific details included within the `java.lang.UnsatisfiedLinkError` you receive? Also, how/where does your application initialize SQLCipher?

**Comment by nic-bell** [comment]
Hi @developernotes. 
The error happens with `loadLibraries` which gets called by a content provider onCreate. I've never been able to reproduce it myself but see it appearing in Crashlytics periodically. Usually on a Samsung Android 8 device running in the background.

![image](https://user-images.githubusercontent.com/57101173/102790094-e3c17e00-439c-11eb-97b5-cd1c5dee6d2d.png)

**Comment by developernotes** [comment]
Hi @nic-bell 

Thank you for sharing some additional information related to the behavior you are seeing. Please feel free to reach out to us at [support@zetetic.net](mailto:support@zetetic.net) to discuss further support options. Thanks!

**Comment by nic-bell** [comment]
Thanks @developernotes I've been digging around a bit more it looks like `UnsatisfiedLinkError` can happen with Android  bundles when the user moves the app to a SD card.

https://issuetracker.google.com/issues/127691101

https://github.com/android/ndk/issues/979

**Comment by developernotes** [comment]
Hi @nic-bell 

That is a very interesting find. It appears the recommendation is to utilize the following settings:

`extractNativeLibs=true` in AndroidManifest.xml
`android.bundle.enableUncompressedNativeLibs=false` in gradle.properties

If you opt to make those changes, would you please let us know your results?

**Comment by nic-bell** [comment]
@developernotes hope you had a good Christmas break. We've deployed the changes and will keep an eye on Crashlytics.

**Comment by developernotes** [comment]
Hi @nic-bell 

>hope you had a good Christmas break. 

Same to you!

>We've deployed the changes and will keep an eye on Crashlytics.

Excellent, thank you for keeping us in the loop, hopefully that addresses the issue.

**Comment by arifurrhman** [comment]
Done the following changes but crashes are still happening

extractNativeLibs=true in AndroidManifest.xml
android.bundle.enableUncompressedNativeLibs=false in gradle.properties

**Comment by nic-bell** [comment]
@arifurrhman there are a lot of reasons you have a crash with this, is your stack trace similar to the one I have in the screen shot above? `dlopen failed: couldn't map "/mnt/asec/...`

**Comment by arifur-chefling** [comment]
@nic-bell No. Mine says **Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.my.package.name-1/base.apk"],nativeLibraryDirectories=[/data/app/com.my.package.name-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libsqlcipher.so"**

**Comment by developernotes** [comment]
Hi @arifur-chefling 

Would you please review the previous feedback posted [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/530#issuecomment-747719360) and provide your results?

**Comment by arifur-chefling** [comment]
@developernotes Yes it is there in x86 folder

**Comment by rafakob** [comment]
Hello! I have the same problem on production. Nexus 5X with Android 8.1.0 (no root) crashes on:


```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.apppackage-Fs3UU3IflBNZyqPkWERX4A==/base.apk"],nativeLibraryDirectories=[/data/app/com.apppackage-Fs3UU3IflBNZyqPkWERX4A==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libsqlcipher.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:227)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:244)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:223)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:216)
       at net.sqlcipher.database.SupportHelper.<init>(SupportHelper.java:31)
       at net.sqlcipher.database.SupportFactory.create(SupportFactory.java:43)
```



I use app bundle with setup:
```
bundle {
    abi {
        enableSplit = true
    }
    density {
        enableSplit true
    }
}
```

The bundle of course includes .so for all ABIs:

![image](https://user-images.githubusercontent.com/6924434/107577531-d41f2280-6bf2-11eb-841e-df170e18e87e.png)


When I unbundle it and check **base-x86.apk** it also has lib:

![image](https://user-images.githubusercontent.com/6924434/107577693-02046700-6bf3-11eb-9acd-4a2fa13bee86.png)

Any other checks that I could make?
