### ISSUE TITLE
 No implementation found for android.os.IBinder net.sqlcipher.CursorWindow.native_getBinder() 

### ISSUE THREAD

**Issue by Hearmen** [sqlcipher/android-database-sqlcipher#553]
### Expected Behavior

When I try to put CursorWindow into intent, it throws an exception

```
    java.lang.UnsatisfiedLinkError: No implementation found for android.os.IBinder net.sqlcipher.CursorWindow.native_getBinder() (tried Java_net_sqlcipher_CursorWindow_native_1getBinder and Java_net_sqlcipher_CursorWindow_native_1getBinder__)
        at net.sqlcipher.CursorWindow.native_getBinder(Native Method)
        at net.sqlcipher.CursorWindow.writeToParcel(CursorWindow.java:632)
        at android.os.Parcel.writeParcelable(Parcel.java:1801)
        at android.os.Parcel.writeValue(Parcel.java:1707)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:928)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1584)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.os.Parcel.writeBundle(Parcel.java:997)
        at android.content.Intent.writeToParcel(Intent.java:10495)
```

So I dig into the source code and find the function was deprecated

```c
  static JNINativeMethod sMethods[] =
    {
      /* name, signature, funcPtr */
      {"native_init", "(ZJJJ)V", (void *)native_init_empty},
      // {"native_init", "(Landroid/os/IBinder;)V", (void *)native_init_memory},
      // {"native_getBinder", "()Landroid/os/IBinder;", (void *)native_getBinder},
```

emmmmm

**Comment by developernotes** [comment]
Hi @Hearmen 

The removal of that feature was at the request of the Google Android team, from a release of SQLCipher for Android to support Android N at the time, in June of 2016. You can read about it [here](https://discuss.zetetic.net/t/sqlcipher-for-android-release-android-n-support/1465?source_topic_id=1251).

**Comment by Hearmen** [comment]
> Hi @Hearmen
> 
> The removal of that feature was at the request of the Google Android team, from a release of SQLCipher for Android to support Android N at the time, in June of 2016. You can read about it [here](https://discuss.zetetic.net/t/sqlcipher-for-android-release-android-n-support/1465?source_topic_id=1251).

got it, thanks
