### ISSUE TITLE
net.sqlcipher.database.SQLiteException: file is not a database

### ISSUE THREAD

**Issue by zhangchaojiong** [sqlcipher/android-database-sqlcipher#558]
SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
4.4.3
SQLCipher for Android version:
4.4.3

i update  SQLCipher for Android   from 4.3.0 to 4.4.3

I get bug log:

```
2021-07-19 15:07:53.176 27541-27541/com.cj.app W/com.cj.app: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
2021-07-19 15:07:53.177 27541-27570/com.cj.app D/ViewContentFactory: initViewContentFetcherClass took 8ms
2021-07-19 15:07:53.177 27541-27570/com.cj.app I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
2021-07-19 15:07:53.177 27541-27570/com.cj.app D/ViewContentFactory: createInterceptor took 8ms
2021-07-19 15:07:53.236 27541-27541/com.cj.app I/Database: JNI_OnLoad called
2021-07-19 15:07:53.236 27541-27541/com.cj.app I/Database: JNI_OnLoad register methods 
2021-07-19 15:07:53.238 27541-27541/com.cj.app V/Database: Registering sqlite logging func 
2021-07-19 15:07:53.239 27541-27541/com.cj.app V/Database: Opened '/data/user/0/com.cj.app/databases/tcl_plus_mall_test.db' - 0xea575108
2021-07-19 15:07:53.240 27541-27541/com.cj.app V/Cursor: Prepared statement 0xe694c1f8 on 0xea575108
2021-07-19 15:07:53.243 27541-27541/com.cj.app V/Cursor: <<< Releasing cursor net.sqlcipher.database.SQLiteCursor@adfd3bb
2021-07-19 15:07:53.243 27541-27541/com.cj.app V/DatabaseWindow: closing window in release()
2021-07-19 15:07:53.244 27541-27541/com.cj.app I/Database: sqlite returned: error code = 283, msg = recovered 46 frames from WAL file /data/user/0/com.cj.app/databases/tcl_plus_mall_test.db-wal
2021-07-19 15:07:53.244 27541-27541/com.cj.app I/Database: sqlite returned: error code = 26, msg = file is not a database in "select count(*) from sqlite_master;"
2021-07-19 15:07:53.246 27541-27541/com.cj.app E/Database: file is not a database: , while compiling: select count(*) from sqlite_master;
    net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
```
Can anyone help me？

**Comment by zhangchaojiong** [comment]
```
1.Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
2.at com.netease.nis.quicklogin.utils.LoginUiHelper.Y(SourceFile:25)
3.at com.netease.nis.quicklogin.utils.LoginUiHelper.G(SourceFile:1)
4.at com.netease.nis.quicklogin.utils.LoginUiHelper$e.onActivityResumed(SourceFile:15)
5.at android.app.Application.dispatchActivityResumed(Application.java:229)
6.at android.app.Activity.onResume(Activity.java:1281)
7.at com.cmic.sso.wy.activity.LoginAuthActivity.onResume(SourceFile:1)
8.at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1276)
9.at android.app.Activity.performResume(Activity.java:6963)
10.at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3469)
11.at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3532)
12.at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
13.at android.os.Handler.dispatchMessage(Handler.java:102)
14.at android.os.Looper.loop(Looper.java:154)
15.at android.app.ActivityThread.main(ActivityThread.java:6211)
16.at java.lang.reflect.Method.invoke(Native Method)
17.at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
18.at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
```

**Comment by zhangchaojiong** [comment]
I got it. the db has not close.

**Comment by developernotes** [comment]
Hi @zhangchaojiong 

We are happy to hear the issue is resolved. Take care!
