### ISSUE TITLE
Crash on Android 6- Unsatisfied Link error when loading library

### ISSUE THREAD

**Issue by sunilcnair** [sqlcipher/android-database-sqlcipher#561]
### Expected Behavior
App should open

### Actual Behavior

App is crashing 

### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version: 4.4.2@aar

Are you able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

*Note:* If you are not posting a specific issue for the SQLCipher library, please post your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mobile.android.myapp-2/base.apk"],nativeLibraryDirectories=[/data/app-lib/com.mobile.android.myapp-2, /data/app/com.mobile.android.myapp-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libsqlcipher.so"
       at java.lang.Runtime.loadLibrary(Runtime.java:367)
       at java.lang.System.loadLibrary(System.java:1076)
       at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:227)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:244)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:223)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:216)
       at net.sqlcipher.database.SupportHelper.<init>(SupportHelper.java:31)
       at net.sqlcipher.database.SupportFactory.create(SupportFactory.java:43)
       at com.android.myt.data.MyDatabase_Impl.createOpenHelper(MyDatabase_Impl.java:216)
       at androidx.room.RoomDatabase.init(RoomDatabase.java:161)
       at androidx.room.RoomDatabase$Builder.build(RoomDatabase.java:953)
       at com.android.myt.data.MyDatabase$Companion.buildDatabase(MyDatabase.java:107)

**Comment by sunilcnair** [comment]
@sjlombardo we are not using any Filters .

**Comment by sjlombardo** [comment]
@sunilcnair it would be worth using the Analyze APK tool to inspect the lib folder and make sure the appropriate libsqlcipher.so is present for armeabi-v7a.

**Comment by Hariharan27** [comment]
Still, we are getting the same issue with the following version 

SQL chiper  - 4.4.2
SQL Lite - 2.2.0

**Comment by developernotes** [comment]
Hi @Hariharan27 

Can you provide comments on your usage of abiFilters, and the results of using APK tool to validate the presence of native libraries within your application? Additionally, what happens when you run the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?
