### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlcipher.so" not found

### ISSUE THREAD

**Issue by iadcialim** [sqlcipher/android-database-sqlcipher#587]
Using android-database-sqlcipher:4.4.3 crashes on Samsung Galaxy A32 5G Android 11

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlcipher.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
       at java.lang.System.loadLibrary(System.java:1664)
       at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:227)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:244)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:223)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:216)
       at net.sqlcipher.database.SupportHelper.<init>(SupportHelper.java:31)
       at net.sqlcipher.database.SupportFactory.create(SupportFactory.java:43)
```

**Comment by developernotes** [comment]
Hi @iadcialim,

What were your results from running the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on the Samsung Galaxy A32 5G Android 11?

**Comment by iadcialim** [comment]
hi @developernotes  I have difficulty verifying this as I got the device information from firebase crashlytics.

**Comment by ItzNotABug** [comment]
There are always going to be some erratic devices that would simply throw an `UnsatisfiedLinkError` due to internal loading issues. I solved this issue by subclassing the `SupportHelper` and `SupportFactory` & used [ReLinker](https://github.com/KeepSafe/ReLinker) to load the libraries if the System failed with an Exception.

Using `android-database-sqlcipher:4.5.1`.

**Comment by iadcialim** [comment]
Hi @ItzNotABug Can you share the full source code? Much appreciated.

**Comment by ItzNotABug** [comment]
@iadcialim Sure.
1. SupportFactory.kt
```kotlin
class SupportFactory @JvmOverloads constructor(
    private val passphrase: ByteArray,
    private val hook: SQLiteDatabaseHook? = null,
    private val clearPassphrase: Boolean = true
) :
    SupportSQLiteOpenHelper.Factory {
    override fun create(configuration: SupportSQLiteOpenHelper.Configuration): SupportSQLiteOpenHelper {
        return SupportHelper(configuration, passphrase, hook, clearPassphrase)
    }
}
```

2. SupportHelper.kt
```kotlin
class SupportHelper internal constructor(
    configuration: SupportSQLiteOpenHelper.Configuration,
    private val passphrase: ByteArray?, hook: SQLiteDatabaseHook?,
    private val clearPassphrase: Boolean
) : SupportSQLiteOpenHelper {

    // Other Java to Kotlin converted functions.
    
    companion object {
        fun loadSqlCipherLibrary(context: Context, libraryLoadedlistener: (Boolean) -> Unit) {
            val libraryName = "sqlcipher"
            try {
                System.loadLibrary(libraryName)
                libraryLoadedlistener(true)
            } catch (exception: UnsatisfiedLinkError) {
                ReLinker.loadLibrary(context, libraryName, object : ReLinker.LoadListener {
                    override fun success() = libraryLoadedlistener(true)
                    override fun failure(t: Throwable?) = libraryLoadedlistener(false)
                })
            }
        }
    }
}
```

And use it like before:
```kotlin
SupportHelper.loadSqlCipherLibrary(appContext) { status ->
    val pass = SQLiteDatabase.getBytes(appContext.strongBlob())
    val roomBuilder = Room.databaseBuilder(
        appContext, AppDatabase::class.java, "app_database"
    )

    if (status) roomBuilder.openHelperFactory(SupportFactory(pass))
    else {
        // other measures..
    }
    roomBuilder.build().also { INSTANCE = it }
}
```

**Note:**
1. See that I use a callback as per my requirement, you can change it as you like.
2. I have currently  hardcoded the `"sqlcipher"` library as it is the only one used internally.
Check [SQLiteDatabase.loadLibs(Context, File, LibraryLoader)](https://github.com/sqlcipher/android-database-sqlcipher/blob/2a8eb64ce037a7007c47f7c8b2312074bf6586b1/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L244).
In the future releases if it changes, you'll have to use a for loop like [SQLiteDatabase.loadLibs(Context, File)](https://github.com/sqlcipher/android-database-sqlcipher/blob/2a8eb64ce037a7007c47f7c8b2312074bf6586b1/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L222).

**Comment by Hariharan27** [comment]
Getting same issue on the below mentioned version 
"net.zetetic:android-database-sqlcipher:4.4.2"
"androidx.sqlite:sqlite-ktx:2.2.0"
 on the **Galaxy Tab A7 Lite (SM-T225N)** device it crashes the application 
Note: We are using app bundles

**Comment by 123dma** [comment]
Hi, I'm also facing the problem reported above. I'm using version net.zetetic:android-database-sqlcipher:4.5.0.

`Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlcipher.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
       at java.lang.System.loadLibrary(System.java:1664)
       at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:6)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:9)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:8)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:7)
       at net.sqlcipher.database.SupportHelper.<init>(SupportHelper.java:5)
       at net.sqlcipher.database.SupportFactory.create(SupportFactory.java:8)`

in this topic it was reported that this problem does not occur in version 4.3.0.

https://discuss.zetetic.net/t/link-failure-on-certain-android-devices/4402

I would like to know if it is safe to downgrade until the problem is fixed.

Further details follow.

- Xiaomi - Redmi Note 10 - Android 11
- motorola - moto g(8) plus - Android 10
- LGE - Nexus 5X - Android 8.1.0

**Comment by developernotes** [comment]
Hi @123dma 

While you shouldn't face any technical issues using SQLCipher for Android 4.3.0 now, it is recommended to use the latest version of the library as it includes many improvements. Instead, [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/593#issuecomment-1216728997) is an approach you might consider applying to address the behavior you are experiencing.

**Comment by GordonWu** [comment]
I got same issue on multiple devices,  I'm using version net.zetetic:android-database-sqlcipher:4.5.0. 
for fix that i also try **ReLinker.loadLibrary**, it seem to be reduce some error, but i got the new error below

```
Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libsqlcipher.so'. Looked for: [armeabi-v7a, armeabi], but only found: [].
       at android.app.ActivityThread.installProvider(ActivityThread.java:7416)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6956)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6844)
       at android.app.ActivityThread.access$1300(ActivityThread.java:268)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7814)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

I have been checked apk lib folder, the libsqlcipher.so is exist.

can someone help me to fix that?

**Comment by developernotes** [comment]
Hi @GordonWu 

Thanks for reaching out, I have a few additional questions regarding your situation:

- What version of ReLinker are you using?
- What Android device/OS version do you receive the `MissingLibraryException` on?
- Are you able to reproduce the `MissingLibraryException` yourself on a specific device/OS version? If so, on what?
- Can you share the output of:

```
ReLinker.log(myLogger).loadLibrary(...);
```
- Are you using `abiFilters` in your build configuration?
- Are you deploying your application using Android App Bundles?

**Comment by GordonWu** [comment]
Hi @developernotes Thanks for reply

-  I'm use the lastest version 'com.getkeepsafe.relinker:relinker:1.4.5'
-  It happen on samsung(Galaxy A11) Android 10. 
-  I can't reproduce this issue on my Google Pixel3XL.
-  I will try to add logcat info about Relinker at next release.
-  No abiFilters in my build configuration.
-  yes I'm deploying my application using Android App Bundles.

**Comment by developernotes** [comment]
Hi @GordonWu 

Thanks for your follow-up, that is helpful. Since you are deploying with App Bundles, would you consider another adjustment to the library loading approach with your next release? With ReLinker, would you adjust your usage to provide a `LoadListener` implementation ([see usage](https://github.com/KeepSafe/ReLinker#advanced-usage)), and in the `failure` call, use the [`SplitInstallHelper`](https://developer.android.com/reference/com/google/android/play/core/splitinstall/SplitInstallHelper#loadlibrary) to load your library as that is meant for supporting split APK's.

**Comment by GordonWu** [comment]
Hi @developernotes 

Thanks for the tip! I will try it for next release.

**Comment by GordonWu** [comment]
Hi @developernotes 

Update from here, After deploying the relevant fixes as you suggested, I really don't see any more bug reports like this! Great, thanks!

**Comment by GordonWu** [comment]
Hi @developernotes,

There is no luck :(
I tried the way you said, although not getting MissingLibraryException but it came back
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader ,nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]] couldn't find "libsqlcipher.so".

currently i can do for now is try catch when this error occur, cancel db init and disable related functions.

**Comment by developernotes** [comment]
Hi @GordonWu 

Thank you for your follow-up, that is unfortunate to hear the `SplitInstallHelper` did not resolve the issue. Can you confirm that `java.lang.UnsatisfiedLinkError` is being thrown when you call `loadLibrary` from `SplitInstallHelper`? Additionally, are you using this in conjunction with ReLinker?

**Comment by GordonWu** [comment]
Hi @developernotes 

Yes, I'm use with ReLinker, here the source,  the error thrown is at line `SplitInstallHelper.loadLibrary(context, "sqlcipher")` after Relinker LoadListener#failure

``` kotlin
class SqlCipherInitializer : Initializer<Unit> {
    override fun create(context: Context) {
        CoroutineScope(Dispatchers.IO).launch {
            loadSqlCipherLibrary(context) { succeeded ->
                if (!succeeded) {
                    try {
                        SplitInstallHelper.loadLibrary(context, "sqlcipher")
                        return@loadSqlCipherLibrary
                    } catch (e: Exception) {
                        return@loadSqlCipherLibrary
                    }
                }

               (...some code for init database)
            }
        }
    }

    override fun dependencies(): List<Class<out Initializer<*>>> {
        return emptyList()
    }


    private fun loadSqlCipherLibrary(context: Context, libraryLoadedListener: (Boolean) -> Unit) {
        val libraryName = "sqlcipher"
        try {
            System.loadLibrary(libraryName)
            libraryLoadedListener(true)
        } catch (exception: UnsatisfiedLinkError) {
            ReLinker.loadLibrary(context, libraryName, object : ReLinker.LoadListener {
                override fun success() = libraryLoadedListener(true)
                override fun failure(t: Throwable?) = libraryLoadedListener(false)
            })
        }
    }
}
```

**Comment by iadcialim** [comment]
> There are always going to be some erratic devices that would simply throw an `UnsatisfiedLinkError` due to internal loading issues. I solved this issue by subclassing the `SupportHelper` and `SupportFactory` & used [ReLinker](https://github.com/KeepSafe/ReLinker) to load the libraries if the System failed with an Exception.
> 
> Using `android-database-sqlcipher:4.5.1`.

hi @ItzNotABug thank you for your info and src code here. i just got back to this issue once again.
By the way, I don't see the purpose of subclassing SupportHelper and SupportFactory but I see that this code is the only difference here
```
companion object {
        fun loadSqlCipherLibrary(context: Context, libraryLoadedlistener: (Boolean) -> Unit) {
            val libraryName = "sqlcipher"
            try {
                System.loadLibrary(libraryName)
                libraryLoadedlistener(true)
            } catch (exception: UnsatisfiedLinkError) {
                ReLinker.loadLibrary(context, libraryName, object : ReLinker.LoadListener {
                    override fun success() = libraryLoadedlistener(true)
                    override fun failure(t: Throwable?) = libraryLoadedlistener(false)
                })
            }
        }
    }
```
Or am I missing something? Thanks

**Comment by iadcialim** [comment]
> ```kotlin
> SqlCipherInitializer
> ```

Hi @developernotes @GordonWu Sorry mates. Im a bit confused on the floating src codes and can't figure out on how to use all of them.
We got codes from:
a. https://github.com/sqlcipher/android-database-sqlcipher/issues/587#issuecomment-1143340726
b. https://github.com/sqlcipher/android-database-sqlcipher/issues/587#issuecomment-1246162180
c. https://github.com/sqlcipher/android-database-sqlcipher/issues/593#issuecomment-1216728997

Can someone guide me on the correct sequence of steps on applying these workaround? Much appreciated

**Comment by ItzNotABug** [comment]
> 
> 
> > There are always going to be some erratic devices that would simply throw an `UnsatisfiedLinkError` due to internal loading issues. I solved this issue by subclassing the `SupportHelper` and `SupportFactory` & used [ReLinker](https://github.com/KeepSafe/ReLinker) to load the libraries if the System failed with an Exception.
> 
> > 
> 
> > Using `android-database-sqlcipher:4.5.1`.
> 
> 
> 
> hi @ItzNotABug thank you for your info and src code here. i just got back to this issue once again.
> 
> By the way, I don't see the purpose of subclassing SupportHelper and SupportFactory but I see that this code is the only difference here
> 
> ```
> 
> companion object {
> 
>         fun loadSqlCipherLibrary(context: Context, libraryLoadedlistener: (Boolean) -> Unit) {
> 
>             val libraryName = "sqlcipher"
> 
>             try {
> 
>                 System.loadLibrary(libraryName)
> 
>                 libraryLoadedlistener(true)
> 
>             } catch (exception: UnsatisfiedLinkError) {
> 
>                 ReLinker.loadLibrary(context, libraryName, object : ReLinker.LoadListener {
> 
>                     override fun success() = libraryLoadedlistener(true)
> 
>                     override fun failure(t: Throwable?) = libraryLoadedlistener(false)
> 
>                 })
> 
>             }
> 
>         }
> 
>     }
> 
> ```
> 
> Or am I missing something? Thanks

Yes,
Directly loading the libraries without extending he classes would work just fine.
I had some other requirements at that time which required extending those classes, guess I missed that point & added the whole solution which wasn't necessary.

**Comment by GordonWu** [comment]
> > ```kotlin
> > SqlCipherInitializer
> > ```
> 
> Hi @developernotes @GordonWu Sorry mates. Im a bit confused on the floating src codes and can't figure out on how to use all of them. We got codes from: a. [#587 (comment)](https://github.com/sqlcipher/android-database-sqlcipher/issues/587#issuecomment-1143340726) b. [#587 (comment)](https://github.com/sqlcipher/android-database-sqlcipher/issues/587#issuecomment-1246162180) c. [#593 (comment)](https://github.com/sqlcipher/android-database-sqlcipher/issues/593#issuecomment-1216728997)
> 
> Can someone guide me on the correct sequence of steps on applying these workaround? Much appreciated

Hi, @iadcialim I believe that all floating src codes are pointing to the same thing, we try use `ReLinker`  to solve `dlopen failed: library "libsqlcipher.so" not found` issue, and I also with use `SplitInstallHelper` when use aab to release product.

So, the core idea is start from b. https://github.com/sqlcipher/android-database-sqlcipher/issues/587#issuecomment-1246162180 , and a. https://github.com/sqlcipher/android-database-sqlcipher/issues/587#issuecomment-1143340726 is more completely code, the last c. https://github.com/sqlcipher/android-database-sqlcipher/issues/593#issuecomment-1216728997 is my current use code

BTW, SqlCipherInitializer : Initializer<Unit> is part of [android jetpack's App Startup](https://developer.android.com/topic/libraries/app-startup)

**Comment by iadcialim** [comment]
Thank you for your answers @GordonWu 
1 more question: In what scenario do we need to call `SQLiteDatabase.loadLibs(this);`?
Currently, I do not call this and this library works just fine.

**Comment by GordonWu** [comment]
> 

Ah gosh, @iadcialim I'm very sorry about that,  I just noticed now that I'm replying in the wrong order, 

C. https://github.com/sqlcipher/android-database-sqlcipher/issues/593#issuecomment-1216728997 >>>>
A. https://github.com/sqlcipher/android-database-sqlcipher/issues/587#issuecomment-1143340726  >>>>
B. https://github.com/sqlcipher/android-database-sqlcipher/issues/587#issuecomment-1246162180 

[B. #587](https://github.com/sqlcipher/android-database-sqlcipher/issues/587#issuecomment-1246162180) is my current code, so i do not call this too.

**Comment by iadcialim** [comment]
Ah ok noted @GordonWu thanks mate

**Comment by iadcialim** [comment]
> Thank you for your answers @GordonWu 1 more question: In what scenario do we need to call `SQLiteDatabase.loadLibs(this);`? Currently, I do not call this and this library works just fine.

@developernotes Do you know when should we call this?

**Comment by developernotes** [comment]
Hi @iadcialim 

>Thank you for your answers @GordonWu 1 more question: In what scenario do we need to call SQLiteDatabase.loadLibs(this);? Currently, I do not call this and this library works just fine.

You need to call `SQLiteDatabase.loadLibs(...)` [^1] prior to invoking a SQL operation that will perform encryption/decryption on the database?

[^1]: https://github.com/sqlcipher/android-database-sqlcipher#using-sqlcipher-for-androids-native-api

**Comment by Psijic** [comment]
I got this error just recently. minSdk = 26, "net.zetetic:android-database-sqlcipher:4.5.4"
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader couldn't find "libsqlcipher.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1029)
       at java.lang.System.loadLibrary(System.java:1673)
       at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(:6)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:3)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:2)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:1)
       at net.sqlcipher.database.SupportHelper.<init>(SupportHelper.java:5)
       at net.sqlcipher.database.SupportFactory.create(SupportFactory.java:8)
```
Model:Samsung Galaxy A70
Version:Android 8.1.0
Rooted:Yes
Crash
Date:Sep 26, 2023

Also Nexus 5X Android 12 not rooted affected.

**Comment by goldfish07** [comment]
try this https://github.com/sqlcipher/android-database-sqlcipher/issues/635#issuecomment-1782209894

**Comment by qsdigor** [comment]
I have the same issue as described here. 
I have been using `useLegacyPackaging = true` but with no luck.

**Comment by developernotes** [comment]
Hi @qsdigor,

There appear to be many factors that may cause this issue for some users. Have you tried using [ReLinker](https://github.com/KeepSafe/ReLinker) in conjunction with a call to [`SplitInstallHelper.loadLibrary(...)`](https://developer.android.com/reference/com/google/android/play/core/splitinstall/SplitInstallHelper#loadLibrary(android.content.Context,%20java.lang.String))?

**Comment by ashishgingercube** [comment]
Hi, 
I have replaced SQLiteDatabase.loadLibs(_mContext); with

SQLiteDatabase.loadLibs(_mContext, libraries -> {
    for (String library : libraries) {
        ReLinker.loadLibrary(_mContext, library);
    }
});

But I still get this error

java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlcipher.so" not found

**Comment by developernotes** [comment]
Hi @ashishgingercube,

I believe this is related to your existing issue #643. Would you please keep your replies within the same thread?
