### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by qianxiaojun1** [sqlcipher/android-database-sqlcipher#591]
### Expected Behavior
java.lang.OutOfMemoryError: Failed to allocate a 1282192 byte allocation with 849992 free bytes and 830KB until OOM, target footprint 536870912, growth limit 536870912
### Actual Behavior
java.lang.OutOfMemoryError
### Steps to Reproduce

SQLCipher for Android version: 4.4.2

**When I read a string with a length of 1.28 million characters from the database table, it is an error**

java.lang.OutOfMemoryError: Failed to allocate a 1282192 byte allocation with 849992 free bytes and 830KB until OOM, target footprint 536870912, growth limit 536870912
	at net.sqlcipher.CursorWindow.getString_native(CursorWindow.java)
	at net.sqlcipher.CursorWindow.getString(CursorWindow.java:412)
	at net.sqlcipher.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
	at android.database.CursorWrapper.getString(CursorWrapper.java:141)

by the way , Is There a limit of 1MB on internal assets due to dynamic decompression?

*Note:* If you are not posting a specific issue for the SQLCipher library, please post your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by qianxiaojun1** [comment]
> Hi @qianxiaojun1
> 
> You are limited by the memory available on device, however, you can specify a custom cursor window allocation behavior via `CursorWindow.setCursorWindowAllocation(...)`. You can find an example within the test suite [here](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/app/src/main/java/net/zetetic/tests/LargeDatabaseCursorAccessTest.java). You might also consider updating to the latest release, currently at 4.5.1.

Thanks for your reply,I'll  try updating to the lastest release。
