### ISSUE TITLE
net.sqlcipher.database.SQLiteException: unable to close due to unfinalized statements or unfinished backups: sqlite3_close() failed

### ISSUE THREAD

**Issue by day5678** [sqlcipher/android-database-sqlcipher#650]
When my database is larger than 2GB, it is very likely that this error will occur when initializing the database. I have another user on my end who has 14GB and keeps reporting this error.

error code :  SQLiteDatabase.openOrCreateDatabase(path, pwd, null, hook);

**Comment by sjlombardo** [comment]
Do you have a stack trace?

**Comment by orhanavan** [comment]
same error

**Comment by sjlombardo** [comment]
@orhanavan not enough information to action. Can you provide details?

**Comment by orhanavan** [comment]
main (native):tid=1 systid=16913
#00 pc 0x2ccd2c base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#01 pc 0x253038 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#02 pc 0x254ef4 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#03 pc 0x25e5ec base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#04 pc 0x253400 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#05 pc 0xd1688 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#06 pc 0xcfdd4 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#07 pc 0xcf988 base.apk (sqlcipher_codec_key_derive + 52) (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#08 pc 0xf3170 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#09 pc 0xfb2a4 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#10 pc 0xfac54 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#11 pc 0xcae14 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#12 pc 0x121a78 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#13 pc 0xefcf0 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#14 pc 0xe435c base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#15 pc 0x17b96c base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#16 pc 0x1720f4 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#17 pc 0x17b178 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#18 pc 0x14dbc4 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#19 pc 0x13a26c base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#20 pc 0xe94e8 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#21 pc 0x1325d0 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#22 pc 0xe7dd4 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#23 pc 0xe8230 base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#24 pc 0xe836c base.apk (sqlite3_prepare16_v2 + 40) (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#25 pc 0x22846c base.apk (sqlcipher::compile + 184) (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#26 pc 0x2286cc base.apk + 20922368 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
       at net.sqlcipher.database.SQLiteCompiledSql.native_compile(SQLiteCompiledSql.java)
       at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:89)
       at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
       at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:91)
       at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
       at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
       at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2016)
       at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1902)
       at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2669)
       at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2599)
       at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1247)
       at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1322)
       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:166)
       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:135)
       at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:131)
       at com.myproject.sts.database.managers.STSDatabaseManager.openDatabase(STSDatabaseManager.java:48)
       at com.myproject.sts.database.managers.RecordsDatabaseManager.insertRecord(RecordsDatabaseManager.java:69)
       at com.myproject.sts.StsService.onLocationChanged(StsService.java:127)
       at com.myproject.generallibrary.modules.location.NewLocationWrapper.setLocation(NewLocationWrapper.java:98)
       at com.myproject.generallibrary.modules.location.NewLocationWrapper$1.onLocationResult(NewLocationWrapper.java:64)
       at com.google.android.gms.internal.location.zzds.notifyListener(zzds.java:2)
       at com.google.android.gms.common.api.internal.ListenerHolder.zaa(ListenerHolder.java:2)
       at com.google.android.gms.common.api.internal.zacb.run(zacb.java:1)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8223)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)

**Comment by orhanavan** [comment]
main (native):tid=1 systid=27483 
#00 pc 0xaf33c libc.so (nanosleep + 12) (BuildId: 50118287324a156bc7be11d3d940c7be)
#01 pc 0x6fe24 libc.so (usleep + 80) (BuildId: 50118287324a156bc7be11d3d940c7be)
#02 pc 0xd9224 base.apk + 16859136 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#03 pc 0xec21c base.apk + 16859136 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#04 pc 0xfe680 base.apk + 16859136 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#05 pc 0xfe800 base.apk + 16859136 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#06 pc 0xcadf8 base.apk + 16859136 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#07 pc 0x1136a0 base.apk + 16859136 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#08 pc 0xd9c0c base.apk (sqlite3_step + 268) (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
#09 pc 0x22a680 base.apk + 16859136 (BuildId: 13b843574893b8f5e7a12e53b5f734b3786a045f)
       at net.sqlcipher.database.SQLiteQuery.native_fill_window(SQLiteQuery.java)
       at net.sqlcipher.database.SQLiteQuery.fillWindow(SQLiteQuery.java:80)
       at net.sqlcipher.database.SQLiteCursor.fillWindow(SQLiteCursor.java:324)
       at net.sqlcipher.database.SQLiteCursor.getCount(SQLiteCursor.java:292)
       at net.sqlcipher.AbstractCursor.moveToPosition(AbstractCursor.java:178)
       at net.sqlcipher.AbstractCursor.moveToFirst(AbstractCursor.java:222)
       at android.database.CursorWrapper.moveToFirst(CursorWrapper.java:75)
       at com.myproject.main_service.db.managers.DatabaseManager.getWOText(DatabaseManager.java:5142)
       at com.myproject.Entrance.dialog.DetailDialog.<init>(SourceFile:41)
       at com.myproject.Entrance.activity.EntranceMainActivity.onClick(SourceFile:1310)
       at android.view.View.performClick(View.java:7663)
       at android.view.View.performClickInternal(View.java:7640)
       at android.view.View.-$$Nest$mperformClickInternal(unavailable)
       at android.view.View$PerformClick.run(View.java:30170)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8223)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)

**Comment by orhanavan** [comment]
I don't know the exact reason. Once the database receives this error, it becomes irreversible @sjlombardo

**Comment by developernotes** [comment]
Hi @orhanavan,

Unfortunately, there is not enough information to determine a cause at this point. I should point out the `android-database-sqlcipher` library has been [deprecated](https://github.com/sqlcipher/android-database-sqlcipher/?tab=readme-ov-file#deprecated-library) and the Community edition is no longer receiving updates. You should consider [migrating](https://www.zetetic.net/sqlcipher/sqlcipher-for-android-migration/) to the long-term replacement library `sqlcipher-android`. It would be helpful to know if you experience the same issue using the new library.

**Comment by orhanavan** [comment]
Thank you! @sjlombardo @developernotes
