### ISSUE TITLE
SQLiteCursor locking issue on close

### ISSUE THREAD

**Issue by madhu314** [sqlcipher/android-database-sqlcipher#97]
In my application which uses a cursorloader I am running into ANR and this is what the trace file looks like. What I am trying to understand here is that why would a main thread which is trying to close the cursor get blocked on itself. This issue happens randomly and I have not yet figured out a reproducible scenario. I am doubting if this is locking issue  associated with sqlcipher's cursor implementation.

"main" prio=5 tid=1 WAIT
  | group="main" sCount=1 dsCount=0 obj=0x415979a0 self=0x4000b010
  | sysTid=9804 nice=0 sched=0/0 cgrp=apps handle=1075102172
  | state=S schedstat=( 0 0 0 ) utm=3670 stm=710 core=1
  at java.lang.Object.wait(Native Method)
- waiting on <0x41597da0> (a java.lang.VMThread) held by tid=1 (main)
  at java.lang.Thread.parkFor(Thread.java:1231)
  at sun.misc.Unsafe.park(Unsafe.java:323)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:810)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:843)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1173)
  at java.util.concurrent.locks.ReentrantLock$FairSync.lock(ReentrantLock.java:198)
  at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:259)
  at net.sqlcipher.database.SQLiteDatabase.lock(SQLiteDatabase.java:460)
  at net.sqlcipher.database.SQLiteProgram.close(SQLiteProgram.java:294)
  at net.sqlcipher.database.SQLiteQuery.close(SQLiteQuery.java:136)
  at net.sqlcipher.database.SQLiteCursor.close(SQLiteCursor.java:510)
  at android.database.CursorWrapper.close(CursorWrapper.java:49)
  at android.database.CursorWrapper.close(CursorWrapper.java:49)
  at android.content.ContentResolver$CursorWrapperInner.close(ContentResolver.java:1860)
  at android.database.MergeCursor.close(MergeCursor.java:175)
  at android.database.CursorWrapper.close(CursorWrapper.java:49)
  at android.content.CursorLoader.deliverResult(CursorLoader.java:117)
  at android.content.CursorLoader.deliverResult(CursorLoader.java:43)

**Comment by narakim** [comment]
I have the exact same issue but it's not easy to reproduce it :( 
@madhu314  did you figure out what the problem was?

**Comment by loommo** [comment]
I have the exact same issue. What can I do for it?

"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 cgrp=default handle=0x400dfbec
  | sysTid=31228 nice=-1 sched=0/0 cgrp=default handle=0x400dfbec
  | state=S schedstat=( 1299270182 324305673 1543 ) utm=102 stm=27 core=3 HZ=100
  | heldMutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x36606923> (a java.lang.Object)
  at java.lang.Thread.parkFor(Thread.java:1233)
  - locked <0x36606923> (a java.lang.Object)
  at sun.misc.Unsafe.park(Unsafe.java:299)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:813)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:846)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1175)
  at java.util.concurrent.locks.ReentrantLock$FairSync.lock(ReentrantLock.java:195)
  at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:256)
  at net.sqlcipher.database.SQLiteDatabase.lock(Taobao:553)
  at net.sqlcipher.database.SQLiteDatabase.addSQLiteClosable(Taobao:480)
  at net.sqlcipher.database.SQLiteProgram.(Taobao:70)
  at net.sqlcipher.database.SQLiteQuery.(Taobao:48)
  at net.sqlcipher.database.SQLiteDirectCursorDriver.query(Taobao:60)
  at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(Taobao:1867)
  at net.sqlcipher.database.SQLiteDatabase.rawQuery(Taobao:1785)

**Comment by developernotes** [comment]
Hi @loommo 

Are you able to create a reproducible test case within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) for further review?
